#  Part of the Parabix Project, under the Open Software License 3.0.
#  SPDX-License-Identifier: OSL-3.0
#
#  Generates test_sorting.cpp:  python3 gen_test_sorting.py test_sorting.cpp
import random, sys
random.seed(2026)
lengths = list(range(1, 71)) + [96, 100, 127, 128, 129, 150, 191, 200]
random.shuffle(lengths)
runs, keys, runlist = [], [], []
pos = 0
for i, L in enumerate(lengths):
    gap = random.randint(1, 3)
    runs += [0]*gap; keys += [0]*gap; pos += gap
    k = [random.randint(1, 6) for _ in range(L)]
    if i % 5 == 0: k.sort()                       # already-ordered runs are left unsorted
    runlist.append((pos, L)); runs += [1]*L; keys += k; pos += L
runs += [0]*3; keys += [0]*3
n = (len(runs) + 3) // 4 * 4
runs += [0]*(n-len(runs)); keys += [0]*(n-len(keys))
payload = [p % 256 for p in range(n)]

def expected(N):
    out = payload[:]
    for start, L in runlist:
        chunk = N if L > N else L
        for c in range(start, start + L, chunk):
            end = min(c + chunk, start + L)
            items = sorted(range(c, end), key=lambda p: (keys[p], p))
            for j, p in enumerate(items): out[c + j] = payload[p]
    return out

def hexstream(bits):
    digits = "".join("%x" % (bits[i] + bits[i+1]*2 + bits[i+2]*4 + bits[i+3]*8) for i in range(0, len(bits), 4))
    return "\n".join('        "%s"' % digits[i:i+96] for i in range(0, len(digits), 96))

def hexset(values, width):
    return ",\n".join(hexstream([(v >> b) & 1 for v in values]) for b in range(width))

out = []
out.append('''/*
 *  Part of the Parabix Project, under the Open Software License 3.0.
 *  SPDX-License-Identifier: OSL-3.0
 */

//  Tests of OddEvenMergeSortRuns.
//
//  The input has runs of every length from 1 to 70 and runs of lengths 96, 100,
//  127, 128, 129, 150, 191 and 200, in random order, separated by 1 to 3 positions.
//  Keys are 3-bit values from 1 to 6; every fifth run is already in order.  The
//  payload at each position is the position mod 256, so the expected payload shows
//  a stable sort: each run (or each chunk of instance_size positions of a longer
//  run, from the run start) sorted by key, with ties in their original order.
//
//  Generated by tests/gen_test_sorting.py; the data is in the static stream notation of
//  testing/stream_gen.hpp: each hex digit holds 4 positions, the first position in
//  its low-order bit.

#include <testing/testing.h>
#include <kernel/streamutils/sorting.h>

using namespace kernel;
using namespace testing;
''')
out.append("auto runs = HexStreamSet({\n%s\n});\n" % hexstream(runs))
out.append("auto keys = HexStreamSet({\n%s\n});\n" % hexset(keys, 3))
out.append("auto payload = HexStreamSet({\n%s\n});\n" % hexset(payload, 8))
for N in (8, 32, 64):
    out.append("auto sorted%d = HexStreamSet({\n%s\n});\n" % (N, hexset(expected(N), 8)))
for fn, tag in (("OddEvenMergeSortRuns", "oddeven"),):
    for N in (8, 32, 64):
        out.append('''TEST_CASE(%s_%d, runs, keys, payload, sorted%d) {
    StreamSets ToSort = {Input<1>(T), Input<2>(T)};
    StreamSets Sorted = %s(P, %d, Input<0>(T), ToSort);
    AssertEQ(P, Sorted[1], Input<3>(T));
}
''' % (tag, N, N, fn, N))
out.append("RUN_TESTS(\n%s\n)\n" % ",\n".join("    CASE(%s_%d)" % (t, N) for t in ("oddeven",) for N in (8, 32, 64)))
open(sys.argv[1], "w").write("\n".join(out))
