#  Part of the Parabix Project, under the Open Software License 3.0.
#  SPDX-License-Identifier: OSL-3.0
#
#  Generates test_sorting.cpp:  python3 gen_test_sorting.py test_sorting.cpp
import random, sys

def make_dataset(lengths, seed):
    rng = random.Random(seed)
    lengths = lengths[:]
    rng.shuffle(lengths)
    runs, keys, runlist = [], [], []
    pos = 0
    for i, L in enumerate(lengths):
        gap = rng.randint(1, 3)
        runs += [0]*gap; keys += [0]*gap; pos += gap
        k = [rng.randint(1, 6) for _ in range(L)]
        if i % 5 == 0: k.sort()                   # already-ordered runs
        runlist.append((pos, L)); runs += [1]*L; keys += k; pos += L
    runs += [0]*3; keys += [0]*3
    n = (len(runs) + 3) // 4 * 4
    runs += [0]*(n-len(runs)); keys += [0]*(n-len(keys))
    payload = [p % 256 for p in range(n)]
    return runs, keys, payload, runlist

def expected(keys, payload, runlist, N=None):
    """Stable sort by key of each run, or of each chunk of N positions of a longer run."""
    out = payload[:]
    for start, L in runlist:
        chunk = N if (N is not None and L > N) else L
        for c in range(start, start + L, chunk):
            end = min(c + chunk, start + L)
            items = sorted(range(c, end), key=lambda p: (keys[p], p))
            for j, p in enumerate(items): out[c + j] = payload[p]
    return out

def hexstream(bits):
    digits = "".join("%x" % (bits[i] + bits[i+1]*2 + bits[i+2]*4 + bits[i+3]*8) for i in range(0, len(bits), 4))
    return "\n".join('        "%s"' % digits[i:i+96] for i in range(0, len(digits), 96))

def hexset(values, width):
    return ",\n".join(hexstream([(v >> b) & 1 for v in values]) for b in range(width))

def streams(name, values, width):
    return "auto %s = HexStreamSet({\n%s\n});\n" % (name, hexset(values, width))

short = make_dataset(list(range(1, 71)) + [96, 100, 127, 128, 129, 150, 191, 200], 2026)
long = make_dataset([300, 1000, 2, 3000, 64, 5000, 129, 65, 7, 1], 2027)

out = []
out.append('''/*
 *  Part of the Parabix Project, under the Open Software License 3.0.
 *  SPDX-License-Identifier: OSL-3.0
 */

//  Tests of OddEvenMergeSortRuns and SeqSortRuns (Misorder_Check and SeqRunSort).
//
//  The short data set has runs of every length from 1 to 70 and runs of lengths
//  96, 100, 127, 128, 129, 150, 191 and 200; the long data set has runs of lengths
//  1, 2, 7, 64, 65, 129, 300, 1000, 3000 and 5000.  Runs are in random order,
//  separated by 1 to 3 positions.  Keys are 3-bit values from 1 to 6; every fifth
//  run is already in order.  The payload at each position is the position mod 256,
//  so the expected payload shows a stable sort: each run sorted by key, with ties
//  in their original order (for OddEvenMergeSortRuns, each chunk of instance_size
//  positions of a longer run, from the run start).
//
//  Generated by tests/gen_test_sorting.py; the data is in the static stream notation of
//  testing/stream_gen.hpp: each hex digit holds 4 positions, the first position in
//  its low-order bit.

#include <testing/testing.h>
#include <kernel/streamutils/sorting.h>

using namespace kernel;
using namespace testing;
''')
runs, keys, payload, runlist = short
out.append(streams("runs", runs, 1))
out.append(streams("keys", keys, 3))
out.append(streams("payload", payload, 8))
for N in (8, 32, 64):
    out.append(streams("sorted%d" % N, expected(keys, payload, runlist, N), 8))
out.append(streams("sorted", expected(keys, payload, runlist), 8))
runs, keys, payload, runlist = long
out.append(streams("long_runs", runs, 1))
out.append(streams("long_keys", keys, 3))
out.append(streams("long_payload", payload, 8))
out.append(streams("long_sorted", expected(keys, payload, runlist), 8))
for N in (8, 32, 64):
    out.append('''TEST_CASE(oddeven_%d, runs, keys, payload, sorted%d) {
    StreamSets ToSort = {Input<1>(T), Input<2>(T)};
    StreamSets Sorted = OddEvenMergeSortRuns(P, %d, Input<0>(T), ToSort);
    AssertEQ(P, Sorted[1], Input<3>(T));
}
''' % (N, N, N))
for name, prefix in (("runsort", ""), ("runsort_long", "long_")):
    out.append('''TEST_CASE(%s, %sruns, %skeys, %spayload, %ssorted) {
    StreamSet * Sorted = P.CreateStreamSet(8);
    SeqSortRuns(P, Input<0>(T), Input<1>(T), Input<2>(T), Sorted);
    AssertEQ(P, Sorted, Input<3>(T));
}
''' % (name, prefix, prefix, prefix, prefix))
cases = ["oddeven_8", "oddeven_32", "oddeven_64", "runsort", "runsort_long"]
out.append("RUN_TESTS(\n%s\n)\n" % ",\n".join("    CASE(%s)" % c for c in cases))
open(sys.argv[1], "w").write("\n".join(out))
