/*
 *  Part of the Parabix Project, under the Open Software License 3.0.
 *  SPDX-License-Identifier: OSL-3.0
 */

//  Tests of OddEvenMergeSortRuns.
//
//  The input has runs of every length from 1 to 70 and runs of lengths 96, 100,
//  127, 128, 129, 150, 191 and 200, in random order, separated by 1 to 3 positions.
//  Keys are 3-bit values from 1 to 6; every fifth run is already in order.  The
//  payload at each position is the position mod 256, so the expected payload shows
//  a stable sort: each run (or each chunk of instance_size positions of a longer
//  run, from the run start) sorted by key, with ties in their original order.
//
//  Generated by tests/gen_test_sorting.py; the data is in the static stream notation of
//  testing/stream_gen.hpp: each hex digit holds 4 positions, the first position in
//  its low-order bit.

#include <testing/testing.h>
#include <kernel/streamutils/sorting.h>

using namespace kernel;
using namespace testing;

auto runs = HexStreamSet({
        "cffffff3effffffffffffff7cfffffffffffcfffffffffffffffffffffffffffffff7ffeffffffffff3ffffffffff7ef"
        "f1ffffffffffffffefffffffffff1ffffffffffffffffcffffffffffffff3efffffffffffffeffffffffffffffffffff"
        "ffffffffffffffff7effffff8fffffffffffffffffffffff7fffffffffff7ffdfffffffffff7fffffffffffffff9ffff"
        "ffffffff7cffffffffffeffffffffffffeffffffffffffffffd3efffffffffffffffffffffffffffffffffffffffffff"
        "ffffff1ffff3fffffffff7eff37cffffffffffffff9fffffffffdffffffffcfffff36effff1ff3fffffff3ffffffffff"
        "8ffff3effffffff8ffffffff7cfcfffffc7cfffffffffffffffffffffffffffffffffffffffffffffff1ffffffffdfff"
        "ff7efffffffffff7cfffffdfff7efffff7efffffffffffffffffffffffffffffff9fffff8fffffffffffffffff8fffff"
        "ff7fffffffffff8ffffffffffffff9fffffffffffffffff1ffffffffffffffff7cffffffffffffffffffffffffffffff"
        "f9f3effffffffffff3fffffffff1fff7cff5fffffff7ffffffffffffffdfffffffffffffff9fffffffffffff1fffffff"
        "ffffffffffffffffffeffffff3fffbffffffffffffffff9ffffffffffffffffcfffffffff7efff1"
});

auto keys = HexStreamSet({
        "c1f0c300454ab814d0ee9f43484d1e8cee5d8995c2a1841455199fc49d6b3fa3d0ff657efeff10f7000f6db3b2089287"
        "60dea54247323072e2ec33e8f2e30fff308ff708ff7000a7806148faae3c2c06a17d2e47eec44c96751ebe86e4b0de7d"
        "67616543bc0cec28047f02bf8ff30000efff0000cfff00000ff6a6da7f290c21bc03d9fed131d716d41ecea9a379ff10"
        "0e100f700c76565d3c03a763475139d328269fc8b2207f3cdb80effffffff3000008fffffffff0000000000effffffff"
        "000000075331bee2d32d64aac20cff3000fff08ff08445f395478371fabca80467b12e368002e218594ad01e41c85da6"
        "866373ef3ef0e7082b7585f8283c5d37883cffffffff100000000cffff300000000ffffffff0000000004b8e9312826f"
        "3f562bde57f98210088d5d4e120c41d7d62429777c28adcd21bc8ef85a9e92c29018ea908e3282aa95855531628ffff7"
        "c70c63a3dfab710cc59deb10477de93f8e6caa51ca8e4181c7e2656dc9c889e93cffff000cfffff0000000ffffff1000"
        "08700868690f65dcb16f1494c181a955cdd0670f2cf1bbc8dd6fd8e244027d214d411e70c98ff00ef30ef30009ba61b2"
        "6182a88cc3040cd7ae0f4aa1403c221e2010a2afd3236e9ff700fff000eff100b866315857ca9a1",
        "0ef00cf30f0436595b0068f6079ac54183c506293c5c6be50f1d0436679cca59afcc74800fff1008ff38924d13a76162"
        "e12dda9deeb8e5ac6f1b0c1b6d771000cffff700008ffc3e9b7cabd6f99034d9eca712bb433ea7494aaf96567d0fa04f"
        "919c8ea743f3d77772c26f04000cffffffff00000000ffff7300183490fd5a8800a8b5213206bde1a9e4b59654c000ef"
        "ff10008f78a93ba3e1b44c263819b83c7e5d42e6575ac8a33310000000000cfffffffffffffff0000000000000000000"
        "ffffff14ddc201992c4aa2e5204000cffffff0000f1d7a2e57ad8f4e8d265459fa2200c70f1711b7712621f3fc70fa60"
        "88bcd100cff008f0f00a692410a0a2dc207000000000efffffffffffff30000000000000000ffffffff12eb6eccc4f35"
        "4838d5b9a9166fe7c20b7e9f1c789ae214e35007aac42460dc487004a12935f19f805f5981cd2c453b7bc544f4000ff7"
        "087bcc4e00f35f83fa62567f22ed904bed073b8b2d7831602c3c36de1a0e965f400000fffffffff0000000000000efff"
        "f1a24c47f07b1bb7425b897f5e2172e40e1547f1de06651bfee1771c93d648de83776109db100ffff3000cff10420034"
        "845f625d53fd5b181de931cf315ff2d0d44204906c49f11008fffff000000efc558edeffe187440",
        "000ffff3e8f74fab26171534cb676ab211b2c9d6b9c6769ab0e2730b387675342d210a000000efffff35a48eccd8e70c"
        "11437a2b31cf1bc58996df2617880000000008fffffff4c97493f50912eb12f756c8f1a0b950d2f78cd16139835f7bb2"
        "4e5279dcfc5618942e15f858000000000000ffffffffffff709bf30986527555e7d64eca4dc040cb3fc1285eeb210000"
        "00efffff749b8c76476f0399b1aec781d68abd39c8bfa65fecc30000000000000000000000000fffffffffffffffffff"
        "ffffff18a0027f342e93d10b3370000000000fffff9386596838588414cb3cfb1dd24008ff1813cc8e99f3a52297a25f"
        "09922200000ffff054a412cf5440014054000000000000000000000000cffffffffffffffffffffffff1f1414cad5092"
        "f1001001d4497824cd728310ef723d2ca14cb7e81137d3be43e7e1e744e6cc1c648f01e70c18f3986ae42abe0d000008"
        "ff70967d385486811b5f9189f91239d432d154ecf513aed179999b03b67570a4100000000000000fffffffffffffffff"
        "f143a79007c0c408a2b0732b2ed0c42300e5982e03d116b4019cad65be4993dd3c9ae4d6240000000cffffff16159fcb"
        "fe70d7e23c9ae1a4c0e28776b281d9a14bbf7f4b3bf683000000000ffffffff427f96f2424282b1"
});

auto payload = HexStreamSet({
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
        "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
        "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
        "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
        "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
        "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
        "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
        "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
        "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
        "ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
        "0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
        "0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
        "0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
        "0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
        "0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
        "0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
        "0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
        "0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
        "0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
        "0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0",
        "00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff"
        "00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff"
        "00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff"
        "00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff"
        "00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff"
        "00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff"
        "00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff"
        "00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff"
        "00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff"
        "00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00f",
        "0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff"
        "0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff"
        "0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff"
        "0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff"
        "0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff"
        "0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff"
        "0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff"
        "0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff"
        "0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff"
        "0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000fff",
        "00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff"
        "00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff"
        "00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff"
        "00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff"
        "00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff"
        "00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff"
        "00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff"
        "00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff"
        "00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff"
        "00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000fffffff",
        "0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff"
        "0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff"
        "0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff"
        "0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff"
        "0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff"
        "0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff"
        "0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff"
        "0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff"
        "0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff"
        "0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff000000000000000",
        "00000000000000000000000000000000ffffffffffffffffffffffffffffffff00000000000000000000000000000000"
        "ffffffffffffffffffffffffffffffff00000000000000000000000000000000ffffffffffffffffffffffffffffffff"
        "00000000000000000000000000000000ffffffffffffffffffffffffffffffff00000000000000000000000000000000"
        "ffffffffffffffffffffffffffffffff00000000000000000000000000000000ffffffffffffffffffffffffffffffff"
        "00000000000000000000000000000000ffffffffffffffffffffffffffffffff00000000000000000000000000000000"
        "ffffffffffffffffffffffffffffffff00000000000000000000000000000000ffffffffffffffffffffffffffffffff"
        "00000000000000000000000000000000ffffffffffffffffffffffffffffffff00000000000000000000000000000000"
        "ffffffffffffffffffffffffffffffff00000000000000000000000000000000ffffffffffffffffffffffffffffffff"
        "00000000000000000000000000000000ffffffffffffffffffffffffffffffff00000000000000000000000000000000"
        "ffffffffffffffffffffffffffffffff00000000000000000000000000000000fffffffffffffff"
});

auto sorted8 = HexStreamSet({
        "aaaaaaaa23b96c07b2b5e24b2ba36c992f4c6556a1b5632ea13dd2a47995d9c4276a94daaaaaaaaaaaa9ca91b6947aa6"
        "6a65cc4bb82ea3e44b233555758cbaaaaaaaaaaaaaaaa6b86dc89dc0e98b9a9c5c23d4adcc3e0b64d6ca2754de22a17b"
        "2b3c568d6e46a2e6c61ba62baaaaaaaaaaaaaaaaaaaaaaaaa6a47c93ce1c9f0a871f21b9b8aa71c56ae82d55c5aaaaaa"
        "aaaaaaaaaa91978774176197451772d662e85b87c8b0ef20d53baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaa2e55a95a54b9a6c8d4baaaaaaaaaaaaaaaaa237caa2d1baab8c1e5e38598baaaaaaa569561baa99964d350f33"
        "ac22faaaaaaaaaaae88b64baa63ac9dc16aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa69d1c9aa6e8c"
        "6b8a56aa1f16c0db6c652baaaaa878a53ba32b4787aa6a0bb647ac2b6346766297a8e695a9a1e2e0f833b85ab5aaaaaa"
        "aaaa963e8a3b852713b1baa26b19bae06e39d0bcc9a2ad5a3caaa95aca7163279aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aa6ac561754ee4869b87e21d1b1ba52daaaa9c4d9a3ab4c5353c93b2ccea8e49a31cf5865aaaaaaaaaaaaaaaae2b8694"
        "be1c517969a87c6e8907d9658b563a8d527c1bcc46a35baaaaaaaaaaaaaaaaaecc46a61b3a0e3da",
        "cccccccc8a353572b5c92bcc4d8551f2e3ca865d42bc55556557ccc5cc836556523fc8bccccccccccccaa2e8e8d8b925"
        "bca36ad8714d724eaa4789736239dcccccccccccccccc4c2b57c496dcc26d6c495cd5e079664a7a079dc6e28ec52d658"
        "b8de88c9c96374d2bc32655dcccccccccccccccccccccccccb8d4f0cc6a5ccc836c6a2ee81cf4da6394d17c9696ccccc"
        "cccccccccc2d07d4957cc366a52a5537c8674dc8c7389758785ecccccccccccccccccccccccccccccccccccccccccccc"
        "ccccccc4b87c36936ce21e696ccccccccccccccccccc2da1e915133e6ce6c86d21bdccccccc65c0f4d5acc35c356a51d"
        "472bcccccccccccc4d2db017b4dcac8eaccccccccccccccccccccccccccccccccccccccccccccccccccc53960f4e43d6"
        "8ae47c9499da4d9c09f4d3ccccce10f29d2ea58be4e0b98e835cd43c5a5b0f0b1b52f5c64c35372ab15ae51c6dcccccc"
        "ccc1b6c3c4b1e9c992ea952bac9d84cee06b1327ecd8a25d595ad1c3535ca54daccccccccccccccccccccccccccccccc"
        "cc2d615a7a2c9c3c5d3371b89c8d2ee8cccc2d66c34b7896874ec99c9589670cf89d8caa2bdcccccccccccccca55a8b5"
        "caa6c9ad12b4eb48ec29736aac2707bccc5954d9706e9acccccccccccccccccc158f85c17d23f8c",
        "0f0f0f0fe03a1e3cd41f4e2d4839b9dc8567c8da8ae195a787c984371f45a78c197c21ef0f0f0f0f0f093352dd1e1f46"
        "1f8d3c8ea58b4b692d851e935c3e0f0f0f0f0f0f0f0f072f15ad1a879dc41f07c4b6666e03373649935f82bc4935ea60"
        "75761b9e827aca9621bf483f0f0f0f0f0f0f0f0f0f0f0f0f033719c9633f0a9bdc85c927a2fc56a94d63a62d660f0f0f"
        "0f0f0f0f0ba6aa96c6cd0b5dc94c5e4b01b593ec5a54d46d9c9d0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
        "0f0f0f07299f0fe28dac394c9d0f0f0f0f0f0f0f0f84d9433e961d63aa651376c52f0f0f0f087f6a8ecc1e9995933987"
        "81b31f0f0f0f0f0f39c435d4274f0f68274f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f741b6c2d878b"
        "c2179617325d54eec986ad0f0f03bcc4dec626f24d23b23d0fc9e2a17c6caaa8d11c37ab82b62bc32d174e90fe0f0f0f"
        "0f0d1554d72d4f83a43cb9c1b13e17b2b27ca2798693639e6a694b0f696af0a90f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
        "0f8e46d32c37c11b3ed15a8e2e2eb28b0f0fc9870f6c2de22e961da9a90f4a523d9adacc4c1f0f0f0f0f0f0f03693c57"
        "1d2f0d4e2c3d4d8b4fa34abc4d4b6c9a839596965b4b1d0f0f0f0f0f0f0f0f0b4f29ca99ad859e0",
        "00ff00ff04af906f18ef00ff828d36ce28df01ef05cd1ac728ef03c710f728ee944f2e1f00ff00ff00f93ca2d2ee10f7"
        "10ff00ff00ff00ff00f750e790af10ff00ff00ff00ff08f119df04f680f710f5ca5748df0cc728b19daf0ccd46c1ec91"
        "3f87147d8c93cc672eca4ece00ff00ff00ff00ff00ff00ff0cc716396ccf056b18778cd58c3f00ff00ff00ff00ff00ff"
        "00ff00ff04d70e6788bf04ef026f90ef0e541d3d44e1da9992ef00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff"
        "00ff00f7266f00ff00ff00fd10ff00ff00ff00ff00f472b331e7d04f21d71c970dde00ff00f870ff00ff00ff00ff00ff"
        "0ac350ff00ff00ff00f728e728bf00fb28bf00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff08ef"
        "05c718e71cad4a3f06c630ff00f3363590ff40ef00fb14af50cf11af906f10fb306c78df05c7a493326761e870ff00ff"
        "00fd1aa4d8dd40f339cc3693364f187728df08d7887728ef00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff"
        "00ff08eb906f12af10ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00bfa06e32af11dea0ef00ff00ff00ff0c9933a7"
        "12df02be23cd427b40bf14ef00ff087f08e7187748f510ff00ff00ff00ff00fb09fa8c7221bf10f",
        "0000ffff0040ef7f1000ffff0042cffe2000ffff0002eff72000fff71008dffe1080dfff0000ffff0006cff2d001eff7"
        "1000ffff0000ffff0008eff71040efff0000ffff0000fff31100fff78008eff5c008bfff0008dff19100fffd400e1ff1"
        "3108effd800c3ff72004bfff0000ffff0000ffff0000ffff0008eff96000fffb10087ff78000ffff0000ffff0000ffff"
        "0000ffff0008fdf78000ffff0080efff000aeefd400e2ff99000ffff0000ffff0000ffff0000ffff0000ffff0000ffff"
        "0000fff72000ffff0000fffd1000ffff0000ffff000b8ff33008ef7f2008eff70100ffff00078fff0000ffff0000ffff"
        "000cafff0000ffff0008dff72000fffb2000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff"
        "0008eff71002bfff0009cfff000ccff59000ffff0004efbf1020efbf1080effb10838fff0008dff330889ff87000ffff"
        "0002eff4d002bff33003cff33080eff72000fff78008dfff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff"
        "0000fffb1080efbf1000ffff0000ffff0000ffff0000ffff0000ffff0040df7e3040effe2000ffff0000ffff0006cff7"
        "1000fffe2002bffb4040efff0000ffff0008eff74008efff0000ffff0000fffb01047ff32140eff",
        "00000000ffffff7f10000000fffffffe20000000fffffff720000008effffffe10000000ffffffff0000000d2ffffff7"
        "10000000ffffffff00000008efffffff00000000fffffff3110000087ffffff5c0000000fffffff191000002bffffff1"
        "310000027ffffff720000000ffffffff00000000ffffffff000000069ffffffb100000087fffffff00000000ffffffff"
        "00000000fffffff780000000ffffffff00000002bffffff990000000ffffffff00000000ffffffff00000000ffffffff"
        "00000008dfffffff00000002efffffff00000000fffffff330000080dffffff701000000ffffffff00000000ffffffff"
        "00000000ffffffff00000008dffffffb20000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff"
        "00000008efffffff00000000fffffff590000000ffffffbf10000040effffffb10000000fffffff3300000078fffffff"
        "0000000b2ffffff33000000ccffffff7200000087fffffff00000000ffffffff00000000ffffffff00000000ffffffff"
        "00000004efffffbf10000000ffffffff00000000ffffffff00000000ffffff7e30000001dfffffff00000000fffffff7"
        "10000001dffffffb40000000ffffffff00000008bfffffff00000000fffffffb0100000cdefffff",
        "0000000000000080effffffffffffffe2000000000000008dffffffffffffffe1000000000000000fffffffffffffff7"
        "1000000000000000ffffffffffffffff000000000000000ceefffffffffffff5c00000000000000e6efffffffffffff1"
        "3100000000000008dfffffffffffffff0000000000000000fffffffffffffffb1000000000000000ffffffffffffffff"
        "00000000000000087fffffffffffffff00000000000000066fffffffffffffff0000000000000000ffffffffffffffff"
        "0000000000000000ffffffffffffffff000000000000000ccffffffffffffff70100000000000000ffffffffffffffff"
        "0000000000000000fffffffffffffffb2000000000000000ffffffffffffffff0000000000000000ffffffffffffffff"
        "0000000000000000fffffffffffffff59000000000000040effffffffffffffb100000000000000ccfffffffffffffff"
        "000000000000000ccffffffffffffff72000000000000000ffffffffffffffff0000000000000000ffffffffffffffff"
        "0000000000000040efffffffffffffff0000000000000000ffffffffffffff7e3000000000000000fffffffffffffff7"
        "1000000000000004bfffffffffffffff0000000000000000fffffffffffffffb010000000000000",
        "00000000000000000000000000000001dffffffffffffffffffffffffffffffe10000000000000000000000000000008"
        "efffffffffffffffffffffffffffffff0000000000000000000000000000000a3ffffffffffffffffffffffffffffff1"
        "31000000000000000000000000000000fffffffffffffffffffffffffffffffb10000000000000000000000000000000"
        "ffffffffffffffffffffffffffffffff00000000000000000000000000000000ffffffffffffffffffffffffffffffff"
        "00000000000000000000000000000000fffffffffffffffffffffffffffffff701000000000000000000000000000000"
        "fffffffffffffffffffffffffffffffb20000000000000000000000000000000ffffffffffffffffffffffffffffffff"
        "0000000000000000000000000000000a6ffffffffffffffffffffffffffffffb10000000000000000000000000000000"
        "fffffffffffffffffffffffffffffff720000000000000000000000000000000ffffffffffffffffffffffffffffffff"
        "00000000000000000000000000000000ffffffffffffffffffffffffffffff7e30000000000000000000000000000008"
        "efffffffffffffffffffffffffffffff00000000000000000000000000000004fefffffffffffff"
});

auto sorted32 = HexStreamSet({
        "aaaaaaaa612b17e27fca648a233ab98b1f89a53155d66660e770f6a125bec8d65364a4daaaaaaaaaaaa969948ed4e9ae"
        "2a2a6b278daa3695a247d89a7497aaaaaaaaaaaaaaaaa66f62b09509f2c7927765998447573aee036cce95b24b1cc199"
        "59ecb3668d1e21d6ced8518baaaaaaaaaaaaaaaaaaaaaaaaa68b980fb6d38f0ac354c5d9a3a91e7962aa6069f65aaaaa"
        "aaaaaaaaa2ae5724f45662a68f98deaa2684535ed0633e8ab53baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaa692cb5a43ad1d6c46eaaaaaaaaaaaaaaaaa2b691f28d1bacae4c352bf224baaaaaaa5e8a386a769586169be33"
        "a0f0faaaaaaaaaaa64edaa98a63a8df306aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa92b7522b63c3"
        "d58abe57600b0d6b6b886eaaaaa0cb9d8e2aeaf64169a19e59aa9596b46ac92d63a96ad1af44404ff0704f7e95aaaaaa"
        "aaaaacd93327162df250bc2a3ee8ca727d942133d26c7c5ab2d8c46d47e99a619aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aa6ae84597d22e2acbc681b3ab1b27ccaaaa7232a59ebcb43139b28f4875f5e24493a0df2caaaaaaaaaaaaaaae3a1698"
        "be46d1f12836ac75398cc2fb4a5e1ae4cc31ea2a49ccfaaaaaaaaaaaaaaaaaaeda09585b3c80fea",
        "ccccccccea025ad5b74f984c85be0c53e758486d05fcdac5aa98e74771506274f511f8bcccccccccccca02175bf87a23"
        "bca9f79045c345cd478ef18c6925dcccccccccccccccc4c1bd9c197dc494d2b216ecee712e22427ea5d6b65d1512cb95"
        "963e0a0a2f7b4cb3a49667accccccccccccccccccccccccccbfc2819ae44dcc841913b7f04fbc41d393e10ffb08dcccc"
        "cccccccccc3e0a4735f8cdf18b203b4ba05d614f69b1b1d3385ecccccccccccccccccccccccccccccccccccccccccccc"
        "ccccccc0c75d33df26061ee54ccccccccccccccccc4fc68a613514a27fcec454b65dccccccc65c142b27fc5b363e241d"
        "4b728ecccccccccc4da6c0e6b4dce8a9accccccccccccccccccccccccccccccccccccccccccccccccccc144bd8cfcd68"
        "d0d469f46c13d1adc8e273ccccc6ae46caa334772a6ce640d5d2150ddb108de7b55d54e5406f627d91e8ace86dcccccc"
        "ccc939310fb54bc71d38b89d4f6144e0e397d0e4d4a7315d553fc54159cb2c5aaccccccccccccccccccccccccccccccc"
        "cc2dc35c254b544e7dfe2d500d8d2abacccc0bd4b9d8718e52ab52273b8e2660ee152ad7d2dccccccccccccccad1aab8"
        "ce68b88b5344c6a77ce9c61cac2317bd58a5857b9b908bccccccccccccccccccf0902db17bae1ac",
        "0f0f0f0fad00a4ef1a78aeec854709ed9b658e63762413f7f0a0988eb794a8ce8d9831ef0f0f0f0f0f0d05b6656ebc44"
        "afc0d91d97238f1b0c272dce51cb1f0f0f0f0f0f0f0f07fb182b1ab19ce507f839b0563d54437730c96387e9a3831c79"
        "1bb6dc721e2ab127256b74b90f0f0f0f0f0f0f0f0f0f0f0f0339ec623be60a9b55a66696473d5616fa43a4983bce0f0f"
        "0f0f0f0f0b29cc6ab6cb06e511f35b8511af18977c49d8d8dc9d0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
        "0f0f0f07e46e447a077e3901fd0f0f0f0f0f0f0f0f88c3d94e9619ed419e1f88e46f0f0f0f08fec4ccc78ef131e74887"
        "8d1cdc0f0f0f0f0f7ac45e24274fc649474f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0fd68d059d077d"
        "1907b39cc8a87e2d8dc3cc0f0f0353d67a2d47bda0e0ca96a7ea1ef90075f107c41c677a8a97346a153636bcce0f0f0f"
        "0f05cf50553d9d83314d5da693c2762fbb063251f5d8a19ea42daa5dafec210b0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
        "0f8ecd14c99d07b46e35c580df2e31790f0f006f3f1da6d892d3a645a3985db8789db469d40f0f0f0f0f0f0f0313fcd4"
        "157bdc222d86fe02afa875e0dc4b6c384fc9465321f6bc0f0f0f0f0f0f0f0f0b1b1587d9ab0b2f0",
        "00ff00ffa24c3739d3123f0f8993d17212fb03bb58b81c99fc312b35a1e4fc68e5e20e1f00ff00ff00f13a3876ee20f5"
        "a03f91a5163ee9dd6b36a11391f500ff00ff00ff00ff088dd1b3543e19f6185c50fe98db18b16a15f2bd3781c5699e90"
        "6cb7277320bbc1c53efc2af000ff00ff00ff00ff00ff00ff0cd13dc32cf81563f5c834e576c96760b27cc1272cee00ff"
        "00ff00ff0c2290bfd87f884edd31f3181ab96d14c032e3ecd2ef00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff"
        "00ff00fb374e68fb38a8009761ff00ff00ff00ff007d8a11b7d7d1d09dd41c0f1b7e00ff00f870fe8175c052c58f71ff"
        "0e9013ff00ff00ff83d0acf428bf078d88bf00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff1b5e870e898e"
        "61a7cd1171bc972ecc0c14ff00fb1e94445e87263bae0c1bcd032cdee2d91d46ea688ffd0fe9388c1cb408f370ff00ff"
        "00f906d568f911f5a68e913eeb84683a32d8da67a6193aefce5e249942bec17a00ff00ff00ff00ff00ff00ff00ff00ff"
        "00ff6d99c16258374058e71ae1ff4a5d00ffc3680cfbc680e7ad3b48122d91309f36378d17ef00ff00ff00ff0c9fc0ea"
        "12fb113d4ee4494b3038e94fe0f35831b1f19a9a2ef811ff00ff00ff00ff00f39bd63912223372f",
        "0000ffffc270c74e1c9b307fc1e5e18320003c3e9f306f11c0cdf336c707c07f0e33cfff0000ffff000eb3208771dff5"
        "a0cd1226e7f33e6e833c3e1c1200efff0000ffff0000ff0e11cd972f1e80e3906e3f1f9d103283a9fc3628f1f9420fde"
        "70c838bf383cf9fa3873b3ce0000ffff0000ffff0000ffff00e9317c7001eff36ef048f6000178b72370f6c530f0ffff"
        "0000ffff00b3e2c3e000f077e1c1efdd30c17ee786a30df0e000ffff0000ffff0000ffff0000ffff0000ffff0000ffff"
        "0000fff30440706dcfc0ff976100ffff0000ffff0081fc12cb18e1ee1607e70e2c70ffff00078fe80189ff9389347eff"
        "00276cff0000ffff0c173fc42000f7fdc000ffff0000ffff0000ffff0000ffff0000ffff0000ffff00001c9fe930f17f"
        "4138f1e970c6efdf02f0a8ff000c9d17676017c7c3d007e3f9e340e0fc7e1e870d8ff8be0c0e3f0f26c83f334000ffff"
        "000e08667e36eef937e0e1470c087f4c3c1f9c8937e13cff0b9fc81e8d3f066c0000ffff0000ffff0000ffff0000ffff"
        "00007e1e0e786ebf706e06e4f100ffff0000938fcd1277e00b36b37ed3c116cc1fdb300e9b10ffff0000ffff006d0ffc"
        "148d1eb17f078173c0ce8f81f00cafb1e10eecdcc3e02eff0000ffff0000fff3d3e0c1e322cc8df",
        "00000000ff7fffff10000000fdfffdff3000c3c1e0cf7f11c0893cc938fbf07e0c330000ffffffff00004ccf188ffff5"
        "a0006c5808ffffff00000020efffffff00000000ffffff0c118918d0e37ff390603e1062efc3e3b9fc38d00e06b30fde"
        "78f0c700c7cff9ff30000000ffffffff00000000ffffffff000602008ffffff340800008fffe78b72370093acf0fffff"
        "00000000ffbbfafff0000f883e3effdd340280080ff3fffcf0000000ffffffff00000000ffffffff00000000ffffffff"
        "0000000cfbbf706dcfc000689effffff00000000fff9fe13ef100e11e9f9f70e2c700000ffffffe80101c0ed7efb8fff"
        "00000000ffffffff00000008dffff7fdc0000000ffffffff00000000ffffffff00000000ffffffff0000e36016cff17f"
        "41300e068f3fffff00000000ffff9f976781681814ec0ffbfd0cb301016f1fc7ef000000ffff7fef3001c0008fffffff"
        "0000f18981cffff120008189f7ff9f08301c90fec9fecfff00000000ffffffff00000000ffffffff00000000ffffffff"
        "000081e3f1877ebf708118010effffff00006c7032ed77e00b364c812cfd17fc9f10c97060efffff00000000fffffffe"
        "180020408fe7ff7bf00110300fffff31e1008067fc1fffff00000000fffffff31000010cddfffff",
        "0000000000800000effffffffdfffdff30000000000080ee3f76cffffffff07e0c33000000000000fffffffffffffff5"
        "a000000000000000ffffffffffffffff00000000000000f3ee76effffffff390603e1000000c1c4603cffffffff30fde"
        "78f0000000000600cfffffffffffffff0000000000000000fffffffffffffff34080000000008748dc8fffffffffffff"
        "00000000004405000fffffffffffffdd30000000000c00030fffffffffffffff0000000000000000ffffffffffffffff"
        "0000000000008f92303fffffffffffff00000000000601ec10effffffffff70e2c70000000000017fefe3fffffffffff"
        "0000000000000000fffffffffffff7fdc000000000000000ffffffffffffffff0000000000000000fffffffffffff17f"
        "4130000000000000ffffffffffff9f97670000000003f00402ffffffff7f1fc7ef00000000008010cfffffffffffffff"
        "000000000000000edfff7effffffff08301c900000000000ffffffffffffffff0000000000000000ffffffffffffffff"
        "00000000000081408fffffffffffffff000000000000881ff4c9fffffffd17fc9f10000000000000fffffffffffffffe"
        "10000000001800840fffffffffffff31e100800000000000fffffffffffffff3100001000000000",
        "00000000000000000000000002000200cffffffffffffffffffffffffffff07e0c33000000000000000000000000000a"
        "5fffffffffffffffffffffffffffffff00000000000000000000000000000c6f9fc1effffffffffffffffffffff30fde"
        "78f00000000000000000000000000000fffffffffffffffffffffffffffffff340800000000000000000000000000000"
        "ffffffffffffffffffffffffffffffdd30000000000000000000000000000000ffffffffffffffffffffffffffffffff"
        "00000000000000000000000000000000fffffffffffffffffffffffffffff70e2c700000000000000000000000000000"
        "fffffffffffffffffffffffffffff7fdc0000000000000000000000000000000fffffffffffffffffffffffffffff17f"
        "4130000000000000000000000000606898ffffffffffffffffffffffff7f1fc7ef000000000000000000000000000000"
        "ffffffffffffffffffffffffffffff08301c9000000000000000000000000000ffffffffffffffffffffffffffffffff"
        "00000000000000000000000000000000fffffffffffffffffffffffffffd17fc9f100000000000000000000000000001"
        "efffffffffffffffffffffffffffff31e100800000000000000000000000000ceffffefffffffff"
});

auto sorted64 = HexStreamSet({
        "aaaaaaaa6b7954473e1c1aca2333a17b5c99a5d433025fdba1c4f63ae60753965634a4daaaaaaaaaaaa9625940dfd9ae"
        "2a2ca5d2f0371ce5a688e5ae8da6aaaaaaaaaaaaaaaaa62b1b5eb2381f23922ede4d59c7443aefe44da81d81b91cced5"
        "4472b216bb1e21d6ced8518baaaaaaaaaaaaaaaaaaaaaaaaa6837945cef48f0a8a77a015757a163f05aa92f6aa5aaaaa"
        "aaaaaaaaa2adeab406f462a6d85f35193602caa9915e74b9b53baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaa692cb5a8e11b34f46eaaaaaaaaaaaaaaaaa2bd660f40bbaa9a31f42bf224baaaaaaa5e8a386a76952d2c54b57"
        "a0f0faaaaaaaaaaa64eb5556863a8df306aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa92b7524673c3"
        "d58abe5d3499046b6b886eaaaaa0cb9d8e265da6d9b1965658aadc497a21d6b652a96ad1af14483180cfafcf95aaaaaa"
        "aaaaa6fe28ec842d9baa6cd1682bca7343eab521b4c27c5ab25e43e9c922db619aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aa6ae284d556a5b17ac623c6a47b27ccaaaa7232a59eb3e5a434c6e168797f8a24ddf2804daaaaaaaaaaaaaaae378475"
        "85a3ecd1287c82d7538cc2fb4a5e1ae5484a97229dc7daaaaaaaaaaaaaaaaaae6b58461cad80fea",
        "cccccccced3a61e4a42b275c8d7bea10ea1a4ca5565e0a6ae38be790d3b5f53a0181f8bcccccccccccca04817b67fa23"
        "bca1eff50aa04aad4f82dacf1823dcccccccccccccccc83e6c633d929932d2ff4522817e6722652db55374b6aa12c70d"
        "613a2dacd87b4cb3a49667accccccccccccccccccccccccccbf4b30d0255dcc8c82826cededecc0285ffc9b03e8dcccc"
        "ccccccccccbc60d9e439cddb3017d601b045fdc88d4f8ed2385ecccccccccccccccccccccccccccccccccccccccccccc"
        "ccccccc0c75d33bd61c88de54ccccccccccccccccc479d1aac26146dcd3b3454b65dccccccc65c142b27fc577c68c51a"
        "4b728ecccccccccc4d4d81a7b4dce8a9accccccccccccccccccccccccccccccccccccccccccccccccccc144bd09fdd68"
        "d0d469d35781c5adc8e273ccccc6ae46caa746b3aed1488475d218007b0e7ddbb55d54e54036f271552bbe986dcccccc"
        "ccc933e9803cfac774d78ed07126446e14c7a5e2da71315d55d29cfbc2c2ba0aaccccccccccccccccccccccccccccccc"
        "cc2dc52588b461ddddfe4a5190ad2abacccc0bd4b9d87d048e5a84fe2b82d290b6d875cde1dcccccccccccccca5fd08b"
        "ae2114eb53880b7a77e9c61cac2317beddcc05b6380cabccccccccccccccccccc39c18cedaae1ac",
        "0f0f0f0fa0dd814149acbffc89747d025fc582bd9f73738c4282982226ff89f2999831ef0f0f0f0f0f0d0aeb6eaa6c44"
        "afc449760c7d9c3b08d2e033d4bf1f0f0f0f0f0f0f0f0bbfb64428ad6b3407bd51fd4a548243367cd9728e070da31b62"
        "ff623648fa2ab127256b74b90f0f0f0f0f0f0f0f0f0f0f0f0339be8774e10a9b5cae4a97856d5652a859ba3b43ce0f0f"
        "0f0f0f0f0ba246adcbba06abb2126bf2119e93a4c697c6e8dc9d0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
        "0f0f0f07e46e44fa44e69b01fd0f0f0f0f0f0f0f0f889b4f98c319c3354a7f88e46f0f0f0f08fec4ccc78ef1624fe624"
        "8d1cdc0f0f0f0f0f7a89ac94274fc649474f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0fd68d052b177d"
        "1907b342f93b861d8dc3cc0f0f0353d67a2f890bba6b9e28e4ead0be70f3780c051c677a8aa97b1c688d359cce0f0f0f"
        "0f05cbf23155dc83b468278bb25b6625e177f38ae684a19ea8ecd4fca21d0a6b0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"
        "0f8ec1d1c61f466a9e358b220aff31790f0f006f3f1da2bdc898aabc839895fa697195f1850f0f0f0f0f0f0f0392f6ad"
        "37b95a022d2debf02aa875e0dc4b6c3a8c09e9332f63bc0f0f0f0f0f0f0f0f0b6cc861ebea0b2f0",
        "00ff00ffae9248897ec6346f81a93eab933903c6ec9b53f075032b3f4329e93c1ed20e1f00ff00ff00f134f38dc2e0f5"
        "a03f7078dec5d0bd6373cc3b19c400ff00ff00ff00ff045c27b7413f7da018c6f8b11878f4b1c7a9c16827db4679939b"
        "7653c880e6bbc1c53efc2af000ff00ff00ff00ff00ff00ff0cd1c3d7674815637fbc82e8197a67ec014e622c7cee00ff"
        "00ff00ff0c24b4c67fdc883dd3ab702312e66d096f14178dd2ef00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff"
        "00ff00fb374e68ddc105229761ff00ff00ff00ff007d1d6c15fad19146735c0f1b7e00ff00f870fe8175c0568b8effb8"
        "0e9013ff00ff00ff839149d728bf078d88bf00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff1b5e870c998e"
        "61a7cd646ed5071ecc0c14ff00fb1e94445ae13c3c8d1bc27d03a12363b56eee2b688ffd0f8e9f58001e4ef070ff00ff"
        "00f90a9e3491e3f58af0d71d346c68b64774453b0b953aefc29769be2c1aec4a00ff00ff00ff00ff00ff00ff00ff00ff"
        "00ff65c9172778901158ef68bd3e4a5d00ffc3680cfbc33690ec34333221e9dc8168d12ef7ef00ff00ff00ff0c19ffb1"
        "38326d8c4ec90584b338e94fe0f358331b613e3c7e8511ff00ff00ff00ff00f34ece8d8c033372f",
        "0000ffffc0e27ec18f08c97fc10e50c30c1234f8f81c930f761cf33c8b3e0ef0e313cfff0000ffff000eb70202fc7ff5"
        "a0c77e90e0766f3e836480c1e107efff0000ffff0000f76037c781c1b137e3f461c99b90f83268311e7cc7e397420c1c"
        "7f9ff0f00b3cf9fa3873b3ce0000ffff0000ffff0000ffff00e1e018b872eff368c0f2010e7478773e9b433070f0ffff"
        "0000ffff0037071870e0f0fdfcb38bb328174ec178e7e701e000ffff0000ffff0000ffff0000ffff0000ffff0000ffff"
        "0000fff3044070e67ef93c976100ffff0000ffff0081e1702a73e1ed781c970e2c70ffff00078fe80189ff9703f0fe3f"
        "00276cff0000ffff0c1e6e172000f7fdc000ffff0000ffff0000ffff0000ffff0000ffff0000ffff00001c9fe970e17f"
        "4138f1b78ff918df02f0a8ff000c9d17676c020837f1e3fc7ae3c2c383c970f0dd8ff8be0cc0e3607edf87614000ffff"
        "000e0463c7e9fcf9dc7c1810c8707fc8897876c3f3193cff036b7e3fc06cc07c0000ffff0000ffff0000ffff0000ffff"
        "000076e1e738ff1d906e0c834e30ffff0000938fcd127b37e00f27cbd3cd31e03081e937f910ffff0000ffff00621bd1"
        "cf3c7ec07f0e06073cce8f81f00cafbb127e30c78f062eff0000ffff0000fff34f0f00b0f3cc8df",
        "00000000f0038f0eff0f0e70f1cf70f3efd3c70ff010e30087ef3c30f3cf002ff3e30000ffffffff0000c8fcf30f8ff5"
        "a0068f1f7f7870cf04870f320e08ffff00000000fffffb70c708f10e3e38f307810e1c1ff0c38f3e108f08f3e78300ef"
        "781cf00ff3cff9ff30000000ffffffff00000000ffffffff000e13e1c08dfff38f0f030e10897087cf1c83cf700fffff"
        "00000000ff37c71f7cf00f3e1f3cf3cf3c1870f18f08f70ef0000000ffffffff00000000ffffffff00000000ffffffff"
        "0000000cfbbf70c468f130689effffff00000000fff1f9703cf30e3687e7e70e2c700000ffffffe80101c0ebfcff77cf"
        "00000000ffffffff00200020cffff7fdc0000000ffffffff00000000ffffffff00000000ffffffff0000e3601e8ff17f"
        "41300e38ff1ef7ef00000000ffff9f97678f0c30c70ef30f7c0cfcf3c30e700f1e000000ff0ff3818f10f7818fffffff"
        "0000f74cf9360ff1e080efe10f708f0f0e70870cf3e1cfff0c7c70cf0f70f08f00000000ffffffff00000000ffffffff"
        "0000870ef7cf70ef1181303c90cfffff00006c7032ed7c38f00cc70c1cf1c10f3ef10e38f1efffff00000000ff7c1c1e"
        "ff308f008fcfc7e7bf0110300fffff3c1cbf300830f7cfff00000000fffffff3701030c00cfffff",
        "000000000ffc70f100f0f18ff1cf70f3efd3080007e30cf10810cf3cf3ff0cfff3f3000000000000fffffffffffffff5"
        "a000000000000000ffffffffffffffff0000000000000c9ff8fffeffcfcff30401081810f00cf1c7eff3ff1c78f3000c"
        "781cf000e3000600cfffffffffffffff0000000000000000fffffffffffffff30800020000008ff8f1e7fcff8fffffff"
        "0000000000c838e0830fffffffbffbff30000006000008100fffffffffffffff0000000000000000ffffffffffffffff"
        "0000000000008f3b970ecfffffffffff00000000000e068fc30cfffffffff70e2c70000000000017fefe3fffffffffff"
        "0000000000000000fffffffffffff7fdc000000000000000ffffffffffffffff0000000000000000fffffffffffff17f"
        "4130000000000000ffffffffffff9f97670030c30000040080fffef3e3ff7effff00000000f00cfef1ef087effffffff"
        "000000000000000e7fffffffff9fff000070040083010000ffffffffffffffff0000000000000000ffffffffffffffff"
        "00000810080000006effffffffffffff00000000000087cf1ff3f8f7eff1c10830e10838f1000000ffffffffff781c1c"
        "ff300f000030381840ffffffffffff301028300000040000fffffffffffffff3400000800000000",
        "0000000000000000000000000e308f0c102cffffffffffffffffff3cf3ff0cfff3f3000000000000000000000000000a"
        "5fffffffffffffffffffffffffffffff00000000000000000000000000000cfbfef7e7ef0ffffffffffffffffff3000c"
        "781cf000e30000000000000000000000fffffffffffffffffffffffffffffff308000200000000000000000000000000"
        "ffffffffffffffffffffffffffbffbff30000000000000000000000000000000ffffffffffffffffffffffffffffffff"
        "00000000000000000000000000000000fffffffffffffffffffffffffffff70e2c700000000000000000000000000000"
        "fffffffffffffffffffffffffffff7fdc0000000000000000000000000000000fffffffffffffffffffffffffffff17f"
        "4130000000000000000000000000606898fffffffffffffffffffef3e3ff7effff000000000000000000000000000000"
        "ffffffffffffffffffffffffffffff0000700400830100000000000000000000ffffffffffffffffffffffffffffffff"
        "00000000000000000000000000000000fffffffffffffffffffffffffff1c10830e10838f1000000000000000087e3e3"
        "00cff0ffffffffffffffffffffffff301028300000040000000000000000000cbfffff7ffffffff"
});

TEST_CASE(oddeven_8, runs, keys, payload, sorted8) {
    StreamSets ToSort = {Input<1>(T), Input<2>(T)};
    StreamSets Sorted = OddEvenMergeSortRuns(P, 8, Input<0>(T), ToSort);
    AssertEQ(P, Sorted[1], Input<3>(T));
}

TEST_CASE(oddeven_32, runs, keys, payload, sorted32) {
    StreamSets ToSort = {Input<1>(T), Input<2>(T)};
    StreamSets Sorted = OddEvenMergeSortRuns(P, 32, Input<0>(T), ToSort);
    AssertEQ(P, Sorted[1], Input<3>(T));
}

TEST_CASE(oddeven_64, runs, keys, payload, sorted64) {
    StreamSets ToSort = {Input<1>(T), Input<2>(T)};
    StreamSets Sorted = OddEvenMergeSortRuns(P, 64, Input<0>(T), ToSort);
    AssertEQ(P, Sorted[1], Input<3>(T));
}

RUN_TESTS(
    CASE(oddeven_8),
    CASE(oddeven_32),
    CASE(oddeven_64)
)
