#ifndef PROPERTYVALUEALIASES_H
#define PROPERTYVALUEALIASES_H
/*
 *  Part of the Parabix Project, under the Open Software License 3.0.
 *  SPDX-License-Identifier: OSL-3.0
 *  2026
 *
 *  This file is generated by UCD_properties.py - manual edits may be lost.
 */

#include <cstdint>
#include <string>
#include <ucd/data/PropertyAliases.h>
#include <unordered_map>
#include <vector>
namespace UCD {

    namespace Binary_ns {
        enum value_t {
            N, Y};
        const static std::vector<std::string> enum_names = {
            "N", "Y"};
        const static std::vector<std::string> value_names = {
            "No", "Yes"};
        static std::unordered_map<std::string, int> aliases_only_map {{
            {"n", N}, {"y", Y}, {"no", N}, {"yes", Y}, {"f", N}, {"t", Y},
            {"false", N}, {"true", Y}}};
    }

    namespace AGE_ns {
        enum value_t {
            Unassigned, V1_1, V2_0, V2_1, V3_0, V3_1, V3_2, V4_0, V4_1,
            V5_0, V5_1, V5_2, V6_0, V6_1, V6_2, V6_3, V7_0, V8_0, V9_0,
            V10_0, V11_0, V12_0, V12_1, V13_0, V14_0, V15_0, V15_1, V16_0,
            V17_0};
        const static std::vector<std::string> enum_names = {
            "Unassigned", "V1_1", "V2_0", "V2_1", "V3_0", "V3_1", "V3_2",
            "V4_0", "V4_1", "V5_0", "V5_1", "V5_2", "V6_0", "V6_1", "V6_2",
            "V6_3", "V7_0", "V8_0", "V9_0", "V10_0", "V11_0", "V12_0",
            "V12_1", "V13_0", "V14_0", "V15_0", "V15_1", "V16_0", "V17_0"};
        const static std::vector<std::string> value_names = {
            "Unassigned", "V1_1", "V2_0", "V2_1", "V3_0", "V3_1", "V3_2",
            "V4_0", "V4_1", "V5_0", "V5_1", "V5_2", "V6_0", "V6_1", "V6_2",
            "V6_3", "V7_0", "V8_0", "V9_0", "V10_0", "V11_0", "V12_0",
            "V12_1", "V13_0", "V14_0", "V15_0", "V15_1", "V16_0", "V17_0"};
        const static std::vector<std::string> aliases = {{
            "NA", "1.1", "2.0", "2.1", "3.0", "3.1", "3.2", "4.0", "4.1",
            "5.0", "5.1", "5.2", "6.0", "6.1", "6.2", "6.3", "7.0", "8.0",
            "9.0", "10.0", "11.0", "12.0", "12.1", "13.0", "14.0", "15.0",
            "15.1", "16.0", "17.0"}};
    }

    namespace BLK_ns {
        enum value_t {
            NB, ASCII, Latin_1_Sup, Latin_Ext_A, Latin_Ext_B, IPA_Ext,
            Modifier_Letters, Diacriticals, Greek, Cyrillic, Cyrillic_Sup,
            Armenian, Hebrew, Arabic, Syriac, Arabic_Sup, Thaana, NKo,
            Samaritan, Mandaic, Syriac_Sup, Arabic_Ext_B, Arabic_Ext_A,
            Devanagari, Bengali, Gurmukhi, Gujarati, Oriya, Tamil, Telugu,
            Kannada, Malayalam, Sinhala, Thai, Lao, Tibetan, Myanmar,
            Georgian, Jamo, Ethiopic, Ethiopic_Sup, Cherokee, UCAS, Ogham,
            Runic, Tagalog, Hanunoo, Buhid, Tagbanwa, Khmer, Mongolian,
            UCAS_Ext, Limbu, Tai_Le, New_Tai_Lue, Khmer_Symbols, Buginese,
            Tai_Tham, Diacriticals_Ext, Balinese, Sundanese, Batak, Lepcha,
            Ol_Chiki, Cyrillic_Ext_C, Georgian_Ext, Sundanese_Sup,
            Vedic_Ext, Phonetic_Ext, Phonetic_Ext_Sup, Diacriticals_Sup,
            Latin_Ext_Additional, Greek_Ext, Punctuation, Super_And_Sub,
            Currency_Symbols, Diacriticals_For_Symbols, Letterlike_Symbols,
            Number_Forms, Arrows, Math_Operators, Misc_Technical,
            Control_Pictures, OCR, Enclosed_Alphanum, Box_Drawing,
            Block_Elements, Geometric_Shapes, Misc_Symbols, Dingbats,
            Misc_Math_Symbols_A, Sup_Arrows_A, Braille, Sup_Arrows_B,
            Misc_Math_Symbols_B, Sup_Math_Operators, Misc_Arrows,
            Glagolitic, Latin_Ext_C, Coptic, Georgian_Sup, Tifinagh,
            Ethiopic_Ext, Cyrillic_Ext_A, Sup_Punctuation, CJK_Radicals_Sup,
            Kangxi, IDC, CJK_Symbols, Hiragana, Katakana, Bopomofo,
            Compat_Jamo, Kanbun, Bopomofo_Ext, CJK_Strokes, Katakana_Ext,
            Enclosed_CJK, CJK_Compat, CJK_Ext_A, Yijing, CJK, Yi_Syllables,
            Yi_Radicals, Lisu, Vai, Cyrillic_Ext_B, Bamum,
            Modifier_Tone_Letters, Latin_Ext_D, Syloti_Nagri,
            Indic_Number_Forms, Phags_Pa, Saurashtra, Devanagari_Ext,
            Kayah_Li, Rejang, Jamo_Ext_A, Javanese, Myanmar_Ext_B, Cham,
            Myanmar_Ext_A, Tai_Viet, Meetei_Mayek_Ext, Ethiopic_Ext_A,
            Latin_Ext_E, Cherokee_Sup, Meetei_Mayek, Hangul, Jamo_Ext_B,
            High_Surrogates, High_PU_Surrogates, Low_Surrogates, PUA,
            CJK_Compat_Ideographs, Alphabetic_PF, Arabic_PF_A, VS,
            Vertical_Forms, Half_Marks, CJK_Compat_Forms, Small_Forms,
            Arabic_PF_B, Half_And_Full_Forms, Specials, Linear_B_Syllabary,
            Linear_B_Ideograms, Aegean_Numbers, Ancient_Greek_Numbers,
            Ancient_Symbols, Phaistos, Lycian, Carian, Coptic_Epact_Numbers,
            Old_Italic, Gothic, Old_Permic, Ugaritic, Old_Persian, Deseret,
            Shavian, Osmanya, Osage, Elbasan, Caucasian_Albanian, Vithkuqi,
            Todhri, Linear_A, Latin_Ext_F, Cypriot_Syllabary,
            Imperial_Aramaic, Palmyrene, Nabataean, Hatran, Phoenician,
            Lydian, Sidetic, Meroitic_Hieroglyphs, Meroitic_Cursive,
            Kharoshthi, Old_South_Arabian, Old_North_Arabian, Manichaean,
            Avestan, Inscriptional_Parthian, Inscriptional_Pahlavi,
            Psalter_Pahlavi, Old_Turkic, Old_Hungarian, Hanifi_Rohingya,
            Garay, Rumi, Yezidi, Arabic_Ext_C, Old_Sogdian, Sogdian,
            Old_Uyghur, Chorasmian, Elymaic, Brahmi, Kaithi, Sora_Sompeng,
            Chakma, Mahajani, Sharada, Sinhala_Archaic_Numbers, Khojki,
            Multani, Khudawadi, Grantha, Tulu_Tigalari, Newa, Tirhuta,
            Siddham, Modi, Mongolian_Sup, Takri, Myanmar_Ext_C, Ahom, Dogra,
            Warang_Citi, Dives_Akuru, Nandinagari, Zanabazar_Square,
            Soyombo, UCAS_Ext_A, Pau_Cin_Hau, Devanagari_Ext_A, Sharada_Sup,
            Sunuwar, Bhaiksuki, Marchen, Masaram_Gondi, Gunjala_Gondi,
            Tolong_Siki, Makasar, Kawi, Lisu_Sup, Tamil_Sup, Cuneiform,
            Cuneiform_Numbers, Early_Dynastic_Cuneiform, Cypro_Minoan,
            Egyptian_Hieroglyphs, Egyptian_Hieroglyph_Format_Controls,
            Egyptian_Hieroglyphs_Ext_A, Anatolian_Hieroglyphs, Gurung_Khema,
            Bamum_Sup, Mro, Tangsa, Bassa_Vah, Pahawh_Hmong, Kirat_Rai,
            Medefaidrin, Beria_Erfe, Miao, Ideographic_Symbols, Tangut,
            Tangut_Components, Khitan_Small_Script, Tangut_Sup,
            Tangut_Components_Sup, Kana_Ext_B, Kana_Sup, Kana_Ext_A,
            Small_Kana_Ext, Nushu, Duployan, Shorthand_Format_Controls,
            Symbols_For_Legacy_Computing_Sup, Misc_Symbols_Sup,
            Znamenny_Music, Byzantine_Music, Music, Ancient_Greek_Music,
            Kaktovik_Numerals, Mayan_Numerals, Tai_Xuan_Jing, Counting_Rod,
            Math_Alphanum, Sutton_SignWriting, Latin_Ext_G, Glagolitic_Sup,
            Cyrillic_Ext_D, Nyiakeng_Puachue_Hmong, Toto, Wancho,
            Nag_Mundari, Ol_Onal, Tai_Yo, Ethiopic_Ext_B, Mende_Kikakui,
            Adlam, Indic_Siyaq_Numbers, Ottoman_Siyaq_Numbers, Arabic_Math,
            Mahjong, Domino, Playing_Cards, Enclosed_Alphanum_Sup,
            Enclosed_Ideographic_Sup, Misc_Pictographs, Emoticons,
            Ornamental_Dingbats, Transport_And_Map, Alchemical,
            Geometric_Shapes_Ext, Sup_Arrows_C, Sup_Symbols_And_Pictographs,
            Chess_Symbols, Symbols_And_Pictographs_Ext_A,
            Symbols_For_Legacy_Computing, CJK_Ext_B, CJK_Ext_C, CJK_Ext_D,
            CJK_Ext_E, CJK_Ext_F, CJK_Ext_I, CJK_Compat_Ideographs_Sup,
            CJK_Ext_G, CJK_Ext_H, CJK_Ext_J, Tags, VS_Sup, Sup_PUA_A,
            Sup_PUA_B};
        const static std::vector<std::string> enum_names = {
            "NB", "ASCII", "Latin_1_Sup", "Latin_Ext_A", "Latin_Ext_B",
            "IPA_Ext", "Modifier_Letters", "Diacriticals", "Greek",
            "Cyrillic", "Cyrillic_Sup", "Armenian", "Hebrew", "Arabic",
            "Syriac", "Arabic_Sup", "Thaana", "NKo", "Samaritan", "Mandaic",
            "Syriac_Sup", "Arabic_Ext_B", "Arabic_Ext_A", "Devanagari",
            "Bengali", "Gurmukhi", "Gujarati", "Oriya", "Tamil", "Telugu",
            "Kannada", "Malayalam", "Sinhala", "Thai", "Lao", "Tibetan",
            "Myanmar", "Georgian", "Jamo", "Ethiopic", "Ethiopic_Sup",
            "Cherokee", "UCAS", "Ogham", "Runic", "Tagalog", "Hanunoo",
            "Buhid", "Tagbanwa", "Khmer", "Mongolian", "UCAS_Ext", "Limbu",
            "Tai_Le", "New_Tai_Lue", "Khmer_Symbols", "Buginese",
            "Tai_Tham", "Diacriticals_Ext", "Balinese", "Sundanese",
            "Batak", "Lepcha", "Ol_Chiki", "Cyrillic_Ext_C", "Georgian_Ext",
            "Sundanese_Sup", "Vedic_Ext", "Phonetic_Ext",
            "Phonetic_Ext_Sup", "Diacriticals_Sup", "Latin_Ext_Additional",
            "Greek_Ext", "Punctuation", "Super_And_Sub", "Currency_Symbols",
            "Diacriticals_For_Symbols", "Letterlike_Symbols",
            "Number_Forms", "Arrows", "Math_Operators", "Misc_Technical",
            "Control_Pictures", "OCR", "Enclosed_Alphanum", "Box_Drawing",
            "Block_Elements", "Geometric_Shapes", "Misc_Symbols",
            "Dingbats", "Misc_Math_Symbols_A", "Sup_Arrows_A", "Braille",
            "Sup_Arrows_B", "Misc_Math_Symbols_B", "Sup_Math_Operators",
            "Misc_Arrows", "Glagolitic", "Latin_Ext_C", "Coptic",
            "Georgian_Sup", "Tifinagh", "Ethiopic_Ext", "Cyrillic_Ext_A",
            "Sup_Punctuation", "CJK_Radicals_Sup", "Kangxi", "IDC",
            "CJK_Symbols", "Hiragana", "Katakana", "Bopomofo",
            "Compat_Jamo", "Kanbun", "Bopomofo_Ext", "CJK_Strokes",
            "Katakana_Ext", "Enclosed_CJK", "CJK_Compat", "CJK_Ext_A",
            "Yijing", "CJK", "Yi_Syllables", "Yi_Radicals", "Lisu", "Vai",
            "Cyrillic_Ext_B", "Bamum", "Modifier_Tone_Letters",
            "Latin_Ext_D", "Syloti_Nagri", "Indic_Number_Forms", "Phags_Pa",
            "Saurashtra", "Devanagari_Ext", "Kayah_Li", "Rejang",
            "Jamo_Ext_A", "Javanese", "Myanmar_Ext_B", "Cham",
            "Myanmar_Ext_A", "Tai_Viet", "Meetei_Mayek_Ext",
            "Ethiopic_Ext_A", "Latin_Ext_E", "Cherokee_Sup", "Meetei_Mayek",
            "Hangul", "Jamo_Ext_B", "High_Surrogates", "High_PU_Surrogates",
            "Low_Surrogates", "PUA", "CJK_Compat_Ideographs",
            "Alphabetic_PF", "Arabic_PF_A", "VS", "Vertical_Forms",
            "Half_Marks", "CJK_Compat_Forms", "Small_Forms", "Arabic_PF_B",
            "Half_And_Full_Forms", "Specials", "Linear_B_Syllabary",
            "Linear_B_Ideograms", "Aegean_Numbers", "Ancient_Greek_Numbers",
            "Ancient_Symbols", "Phaistos", "Lycian", "Carian",
            "Coptic_Epact_Numbers", "Old_Italic", "Gothic", "Old_Permic",
            "Ugaritic", "Old_Persian", "Deseret", "Shavian", "Osmanya",
            "Osage", "Elbasan", "Caucasian_Albanian", "Vithkuqi", "Todhri",
            "Linear_A", "Latin_Ext_F", "Cypriot_Syllabary",
            "Imperial_Aramaic", "Palmyrene", "Nabataean", "Hatran",
            "Phoenician", "Lydian", "Sidetic", "Meroitic_Hieroglyphs",
            "Meroitic_Cursive", "Kharoshthi", "Old_South_Arabian",
            "Old_North_Arabian", "Manichaean", "Avestan",
            "Inscriptional_Parthian", "Inscriptional_Pahlavi",
            "Psalter_Pahlavi", "Old_Turkic", "Old_Hungarian",
            "Hanifi_Rohingya", "Garay", "Rumi", "Yezidi", "Arabic_Ext_C",
            "Old_Sogdian", "Sogdian", "Old_Uyghur", "Chorasmian", "Elymaic",
            "Brahmi", "Kaithi", "Sora_Sompeng", "Chakma", "Mahajani",
            "Sharada", "Sinhala_Archaic_Numbers", "Khojki", "Multani",
            "Khudawadi", "Grantha", "Tulu_Tigalari", "Newa", "Tirhuta",
            "Siddham", "Modi", "Mongolian_Sup", "Takri", "Myanmar_Ext_C",
            "Ahom", "Dogra", "Warang_Citi", "Dives_Akuru", "Nandinagari",
            "Zanabazar_Square", "Soyombo", "UCAS_Ext_A", "Pau_Cin_Hau",
            "Devanagari_Ext_A", "Sharada_Sup", "Sunuwar", "Bhaiksuki",
            "Marchen", "Masaram_Gondi", "Gunjala_Gondi", "Tolong_Siki",
            "Makasar", "Kawi", "Lisu_Sup", "Tamil_Sup", "Cuneiform",
            "Cuneiform_Numbers", "Early_Dynastic_Cuneiform", "Cypro_Minoan",
            "Egyptian_Hieroglyphs", "Egyptian_Hieroglyph_Format_Controls",
            "Egyptian_Hieroglyphs_Ext_A", "Anatolian_Hieroglyphs",
            "Gurung_Khema", "Bamum_Sup", "Mro", "Tangsa", "Bassa_Vah",
            "Pahawh_Hmong", "Kirat_Rai", "Medefaidrin", "Beria_Erfe",
            "Miao", "Ideographic_Symbols", "Tangut", "Tangut_Components",
            "Khitan_Small_Script", "Tangut_Sup", "Tangut_Components_Sup",
            "Kana_Ext_B", "Kana_Sup", "Kana_Ext_A", "Small_Kana_Ext",
            "Nushu", "Duployan", "Shorthand_Format_Controls",
            "Symbols_For_Legacy_Computing_Sup", "Misc_Symbols_Sup",
            "Znamenny_Music", "Byzantine_Music", "Music",
            "Ancient_Greek_Music", "Kaktovik_Numerals", "Mayan_Numerals",
            "Tai_Xuan_Jing", "Counting_Rod", "Math_Alphanum",
            "Sutton_SignWriting", "Latin_Ext_G", "Glagolitic_Sup",
            "Cyrillic_Ext_D", "Nyiakeng_Puachue_Hmong", "Toto", "Wancho",
            "Nag_Mundari", "Ol_Onal", "Tai_Yo", "Ethiopic_Ext_B",
            "Mende_Kikakui", "Adlam", "Indic_Siyaq_Numbers",
            "Ottoman_Siyaq_Numbers", "Arabic_Math", "Mahjong", "Domino",
            "Playing_Cards", "Enclosed_Alphanum_Sup",
            "Enclosed_Ideographic_Sup", "Misc_Pictographs", "Emoticons",
            "Ornamental_Dingbats", "Transport_And_Map", "Alchemical",
            "Geometric_Shapes_Ext", "Sup_Arrows_C",
            "Sup_Symbols_And_Pictographs", "Chess_Symbols",
            "Symbols_And_Pictographs_Ext_A", "Symbols_For_Legacy_Computing",
            "CJK_Ext_B", "CJK_Ext_C", "CJK_Ext_D", "CJK_Ext_E", "CJK_Ext_F",
            "CJK_Ext_I", "CJK_Compat_Ideographs_Sup", "CJK_Ext_G",
            "CJK_Ext_H", "CJK_Ext_J", "Tags", "VS_Sup", "Sup_PUA_A",
            "Sup_PUA_B"};
        const static std::vector<std::string> value_names = {
            "No_Block", "Basic_Latin", "Latin_1_Supplement",
            "Latin_Extended_A", "Latin_Extended_B", "IPA_Extensions",
            "Spacing_Modifier_Letters", "Combining_Diacritical_Marks",
            "Greek_And_Coptic", "Cyrillic", "Cyrillic_Supplement",
            "Armenian", "Hebrew", "Arabic", "Syriac", "Arabic_Supplement",
            "Thaana", "NKo", "Samaritan", "Mandaic", "Syriac_Supplement",
            "Arabic_Extended_B", "Arabic_Extended_A", "Devanagari",
            "Bengali", "Gurmukhi", "Gujarati", "Oriya", "Tamil", "Telugu",
            "Kannada", "Malayalam", "Sinhala", "Thai", "Lao", "Tibetan",
            "Myanmar", "Georgian", "Hangul_Jamo", "Ethiopic",
            "Ethiopic_Supplement", "Cherokee",
            "Unified_Canadian_Aboriginal_Syllabics", "Ogham", "Runic",
            "Tagalog", "Hanunoo", "Buhid", "Tagbanwa", "Khmer", "Mongolian",
            "Unified_Canadian_Aboriginal_Syllabics_Extended", "Limbu",
            "Tai_Le", "New_Tai_Lue", "Khmer_Symbols", "Buginese",
            "Tai_Tham", "Combining_Diacritical_Marks_Extended", "Balinese",
            "Sundanese", "Batak", "Lepcha", "Ol_Chiki",
            "Cyrillic_Extended_C", "Georgian_Extended",
            "Sundanese_Supplement", "Vedic_Extensions",
            "Phonetic_Extensions", "Phonetic_Extensions_Supplement",
            "Combining_Diacritical_Marks_Supplement",
            "Latin_Extended_Additional", "Greek_Extended",
            "General_Punctuation", "Superscripts_And_Subscripts",
            "Currency_Symbols", "Combining_Diacritical_Marks_For_Symbols",
            "Letterlike_Symbols", "Number_Forms", "Arrows",
            "Mathematical_Operators", "Miscellaneous_Technical",
            "Control_Pictures", "Optical_Character_Recognition",
            "Enclosed_Alphanumerics", "Box_Drawing", "Block_Elements",
            "Geometric_Shapes", "Miscellaneous_Symbols", "Dingbats",
            "Miscellaneous_Mathematical_Symbols_A", "Supplemental_Arrows_A",
            "Braille_Patterns", "Supplemental_Arrows_B",
            "Miscellaneous_Mathematical_Symbols_B",
            "Supplemental_Mathematical_Operators",
            "Miscellaneous_Symbols_And_Arrows", "Glagolitic",
            "Latin_Extended_C", "Coptic", "Georgian_Supplement", "Tifinagh",
            "Ethiopic_Extended", "Cyrillic_Extended_A",
            "Supplemental_Punctuation", "CJK_Radicals_Supplement",
            "Kangxi_Radicals", "Ideographic_Description_Characters",
            "CJK_Symbols_And_Punctuation", "Hiragana", "Katakana",
            "Bopomofo", "Hangul_Compatibility_Jamo", "Kanbun",
            "Bopomofo_Extended", "CJK_Strokes",
            "Katakana_Phonetic_Extensions",
            "Enclosed_CJK_Letters_And_Months", "CJK_Compatibility",
            "CJK_Unified_Ideographs_Extension_A", "Yijing_Hexagram_Symbols",
            "CJK_Unified_Ideographs", "Yi_Syllables", "Yi_Radicals", "Lisu",
            "Vai", "Cyrillic_Extended_B", "Bamum", "Modifier_Tone_Letters",
            "Latin_Extended_D", "Syloti_Nagri", "Common_Indic_Number_Forms",
            "Phags_Pa", "Saurashtra", "Devanagari_Extended", "Kayah_Li",
            "Rejang", "Hangul_Jamo_Extended_A", "Javanese",
            "Myanmar_Extended_B", "Cham", "Myanmar_Extended_A", "Tai_Viet",
            "Meetei_Mayek_Extensions", "Ethiopic_Extended_A",
            "Latin_Extended_E", "Cherokee_Supplement", "Meetei_Mayek",
            "Hangul_Syllables", "Hangul_Jamo_Extended_B", "High_Surrogates",
            "High_Private_Use_Surrogates", "Low_Surrogates",
            "Private_Use_Area", "CJK_Compatibility_Ideographs",
            "Alphabetic_Presentation_Forms", "Arabic_Presentation_Forms_A",
            "Variation_Selectors", "Vertical_Forms", "Combining_Half_Marks",
            "CJK_Compatibility_Forms", "Small_Form_Variants",
            "Arabic_Presentation_Forms_B", "Halfwidth_And_Fullwidth_Forms",
            "Specials", "Linear_B_Syllabary", "Linear_B_Ideograms",
            "Aegean_Numbers", "Ancient_Greek_Numbers", "Ancient_Symbols",
            "Phaistos_Disc", "Lycian", "Carian", "Coptic_Epact_Numbers",
            "Old_Italic", "Gothic", "Old_Permic", "Ugaritic", "Old_Persian",
            "Deseret", "Shavian", "Osmanya", "Osage", "Elbasan",
            "Caucasian_Albanian", "Vithkuqi", "Todhri", "Linear_A",
            "Latin_Extended_F", "Cypriot_Syllabary", "Imperial_Aramaic",
            "Palmyrene", "Nabataean", "Hatran", "Phoenician", "Lydian",
            "Sidetic", "Meroitic_Hieroglyphs", "Meroitic_Cursive",
            "Kharoshthi", "Old_South_Arabian", "Old_North_Arabian",
            "Manichaean", "Avestan", "Inscriptional_Parthian",
            "Inscriptional_Pahlavi", "Psalter_Pahlavi", "Old_Turkic",
            "Old_Hungarian", "Hanifi_Rohingya", "Garay",
            "Rumi_Numeral_Symbols", "Yezidi", "Arabic_Extended_C",
            "Old_Sogdian", "Sogdian", "Old_Uyghur", "Chorasmian", "Elymaic",
            "Brahmi", "Kaithi", "Sora_Sompeng", "Chakma", "Mahajani",
            "Sharada", "Sinhala_Archaic_Numbers", "Khojki", "Multani",
            "Khudawadi", "Grantha", "Tulu_Tigalari", "Newa", "Tirhuta",
            "Siddham", "Modi", "Mongolian_Supplement", "Takri",
            "Myanmar_Extended_C", "Ahom", "Dogra", "Warang_Citi",
            "Dives_Akuru", "Nandinagari", "Zanabazar_Square", "Soyombo",
            "Unified_Canadian_Aboriginal_Syllabics_Extended_A",
            "Pau_Cin_Hau", "Devanagari_Extended_A", "Sharada_Supplement",
            "Sunuwar", "Bhaiksuki", "Marchen", "Masaram_Gondi",
            "Gunjala_Gondi", "Tolong_Siki", "Makasar", "Kawi",
            "Lisu_Supplement", "Tamil_Supplement", "Cuneiform",
            "Cuneiform_Numbers_And_Punctuation", "Early_Dynastic_Cuneiform",
            "Cypro_Minoan", "Egyptian_Hieroglyphs",
            "Egyptian_Hieroglyph_Format_Controls",
            "Egyptian_Hieroglyphs_Extended_A", "Anatolian_Hieroglyphs",
            "Gurung_Khema", "Bamum_Supplement", "Mro", "Tangsa",
            "Bassa_Vah", "Pahawh_Hmong", "Kirat_Rai", "Medefaidrin",
            "Beria_Erfe", "Miao", "Ideographic_Symbols_And_Punctuation",
            "Tangut", "Tangut_Components", "Khitan_Small_Script",
            "Tangut_Supplement", "Tangut_Components_Supplement",
            "Kana_Extended_B", "Kana_Supplement", "Kana_Extended_A",
            "Small_Kana_Extension", "Nushu", "Duployan",
            "Shorthand_Format_Controls",
            "Symbols_For_Legacy_Computing_Supplement",
            "Miscellaneous_Symbols_Supplement", "Znamenny_Musical_Notation",
            "Byzantine_Musical_Symbols", "Musical_Symbols",
            "Ancient_Greek_Musical_Notation", "Kaktovik_Numerals",
            "Mayan_Numerals", "Tai_Xuan_Jing_Symbols",
            "Counting_Rod_Numerals", "Mathematical_Alphanumeric_Symbols",
            "Sutton_SignWriting", "Latin_Extended_G",
            "Glagolitic_Supplement", "Cyrillic_Extended_D",
            "Nyiakeng_Puachue_Hmong", "Toto", "Wancho", "Nag_Mundari",
            "Ol_Onal", "Tai_Yo", "Ethiopic_Extended_B", "Mende_Kikakui",
            "Adlam", "Indic_Siyaq_Numbers", "Ottoman_Siyaq_Numbers",
            "Arabic_Mathematical_Alphabetic_Symbols", "Mahjong_Tiles",
            "Domino_Tiles", "Playing_Cards",
            "Enclosed_Alphanumeric_Supplement",
            "Enclosed_Ideographic_Supplement",
            "Miscellaneous_Symbols_And_Pictographs", "Emoticons",
            "Ornamental_Dingbats", "Transport_And_Map_Symbols",
            "Alchemical_Symbols", "Geometric_Shapes_Extended",
            "Supplemental_Arrows_C", "Supplemental_Symbols_And_Pictographs",
            "Chess_Symbols", "Symbols_And_Pictographs_Extended_A",
            "Symbols_For_Legacy_Computing",
            "CJK_Unified_Ideographs_Extension_B",
            "CJK_Unified_Ideographs_Extension_C",
            "CJK_Unified_Ideographs_Extension_D",
            "CJK_Unified_Ideographs_Extension_E",
            "CJK_Unified_Ideographs_Extension_F",
            "CJK_Unified_Ideographs_Extension_I",
            "CJK_Compatibility_Ideographs_Supplement",
            "CJK_Unified_Ideographs_Extension_G",
            "CJK_Unified_Ideographs_Extension_H",
            "CJK_Unified_Ideographs_Extension_J", "Tags",
            "Variation_Selectors_Supplement",
            "Supplementary_Private_Use_Area_A",
            "Supplementary_Private_Use_Area_B"};
        const static std::vector<std::string> aliases = {{
            "", "", "Latin_1", "", "", "", "", "", "", "",
            "Cyrillic_Supplementary", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "Canadian_Syllabics", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "",
            "Combining_Marks_For_Symbols", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "Private_Use", "", "",
            "Arabic_Presentation_Forms-A", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", ""}};
    }

    namespace SC_ns {
        enum value_t {
            Zzzz, Zyyy, Latn, Grek, Cyrl, Armn, Hebr, Arab, Syrc, Thaa,
            Deva, Beng, Guru, Gujr, Orya, Taml, Telu, Knda, Mlym, Sinh,
            Thai, Laoo, Tibt, Mymr, Geor, Hang, Ethi, Cher, Cans, Ogam,
            Runr, Khmr, Mong, Hira, Kana, Bopo, Hani, Yiii, Ital, Goth,
            Dsrt, Zinh, Tglg, Hano, Buhd, Tagb, Limb, Tale, Linb, Ugar,
            Shaw, Osma, Cprt, Brai, Bugi, Copt, Talu, Glag, Tfng, Sylo,
            Xpeo, Khar, Bali, Xsux, Phnx, Phag, Nkoo, Sund, Lepc, Olck,
            Vaii, Saur, Kali, Rjng, Lyci, Cari, Lydi, Cham, Lana, Tavt,
            Avst, Egyp, Samr, Lisu, Bamu, Java, Mtei, Armi, Sarb, Prti,
            Phli, Orkh, Kthi, Batk, Brah, Mand, Cakm, Merc, Mero, Plrd,
            Shrd, Sora, Takr, Aghb, Bass, Dupl, Elba, Gran, Hmng, Khoj,
            Lina, Mahj, Mani, Mend, Modi, Mroo, Narb, Nbat, Palm, Pauc,
            Perm, Phlp, Sidd, Sind, Tirh, Wara, Ahom, Hluw, Hatr, Mult,
            Hung, Sgnw, Adlm, Bhks, Marc, Newa, Osge, Tang, Gonm, Nshu,
            Soyo, Zanb, Dogr, Gong, Maka, Medf, Rohg, Sogd, Sogo, Elym,
            Nand, Hmnp, Wcho, Chrs, Diak, Kits, Yezi, Cpmn, Ougr, Tnsa,
            Toto, Vith, Kawi, Nagm, Gara, Gukh, Krai, Onao, Sunu, Todr,
            Tutg, Sidt, Tayo, Tols, Berf, Hrkt};
        const static std::vector<std::string> enum_names = {
            "Zzzz", "Zyyy", "Latn", "Grek", "Cyrl", "Armn", "Hebr", "Arab",
            "Syrc", "Thaa", "Deva", "Beng", "Guru", "Gujr", "Orya", "Taml",
            "Telu", "Knda", "Mlym", "Sinh", "Thai", "Laoo", "Tibt", "Mymr",
            "Geor", "Hang", "Ethi", "Cher", "Cans", "Ogam", "Runr", "Khmr",
            "Mong", "Hira", "Kana", "Bopo", "Hani", "Yiii", "Ital", "Goth",
            "Dsrt", "Zinh", "Tglg", "Hano", "Buhd", "Tagb", "Limb", "Tale",
            "Linb", "Ugar", "Shaw", "Osma", "Cprt", "Brai", "Bugi", "Copt",
            "Talu", "Glag", "Tfng", "Sylo", "Xpeo", "Khar", "Bali", "Xsux",
            "Phnx", "Phag", "Nkoo", "Sund", "Lepc", "Olck", "Vaii", "Saur",
            "Kali", "Rjng", "Lyci", "Cari", "Lydi", "Cham", "Lana", "Tavt",
            "Avst", "Egyp", "Samr", "Lisu", "Bamu", "Java", "Mtei", "Armi",
            "Sarb", "Prti", "Phli", "Orkh", "Kthi", "Batk", "Brah", "Mand",
            "Cakm", "Merc", "Mero", "Plrd", "Shrd", "Sora", "Takr", "Aghb",
            "Bass", "Dupl", "Elba", "Gran", "Hmng", "Khoj", "Lina", "Mahj",
            "Mani", "Mend", "Modi", "Mroo", "Narb", "Nbat", "Palm", "Pauc",
            "Perm", "Phlp", "Sidd", "Sind", "Tirh", "Wara", "Ahom", "Hluw",
            "Hatr", "Mult", "Hung", "Sgnw", "Adlm", "Bhks", "Marc", "Newa",
            "Osge", "Tang", "Gonm", "Nshu", "Soyo", "Zanb", "Dogr", "Gong",
            "Maka", "Medf", "Rohg", "Sogd", "Sogo", "Elym", "Nand", "Hmnp",
            "Wcho", "Chrs", "Diak", "Kits", "Yezi", "Cpmn", "Ougr", "Tnsa",
            "Toto", "Vith", "Kawi", "Nagm", "Gara", "Gukh", "Krai", "Onao",
            "Sunu", "Todr", "Tutg", "Sidt", "Tayo", "Tols", "Berf", "Hrkt"};
        const static std::vector<std::string> value_names = {
            "Unknown", "Common", "Latin", "Greek", "Cyrillic", "Armenian",
            "Hebrew", "Arabic", "Syriac", "Thaana", "Devanagari", "Bengali",
            "Gurmukhi", "Gujarati", "Oriya", "Tamil", "Telugu", "Kannada",
            "Malayalam", "Sinhala", "Thai", "Lao", "Tibetan", "Myanmar",
            "Georgian", "Hangul", "Ethiopic", "Cherokee",
            "Canadian_Aboriginal", "Ogham", "Runic", "Khmer", "Mongolian",
            "Hiragana", "Katakana", "Bopomofo", "Han", "Yi", "Old_Italic",
            "Gothic", "Deseret", "Inherited", "Tagalog", "Hanunoo", "Buhid",
            "Tagbanwa", "Limbu", "Tai_Le", "Linear_B", "Ugaritic",
            "Shavian", "Osmanya", "Cypriot", "Braille", "Buginese",
            "Coptic", "New_Tai_Lue", "Glagolitic", "Tifinagh",
            "Syloti_Nagri", "Old_Persian", "Kharoshthi", "Balinese",
            "Cuneiform", "Phoenician", "Phags_Pa", "Nko", "Sundanese",
            "Lepcha", "Ol_Chiki", "Vai", "Saurashtra", "Kayah_Li", "Rejang",
            "Lycian", "Carian", "Lydian", "Cham", "Tai_Tham", "Tai_Viet",
            "Avestan", "Egyptian_Hieroglyphs", "Samaritan", "Lisu", "Bamum",
            "Javanese", "Meetei_Mayek", "Imperial_Aramaic",
            "Old_South_Arabian", "Inscriptional_Parthian",
            "Inscriptional_Pahlavi", "Old_Turkic", "Kaithi", "Batak",
            "Brahmi", "Mandaic", "Chakma", "Meroitic_Cursive",
            "Meroitic_Hieroglyphs", "Miao", "Sharada", "Sora_Sompeng",
            "Takri", "Caucasian_Albanian", "Bassa_Vah", "Duployan",
            "Elbasan", "Grantha", "Pahawh_Hmong", "Khojki", "Linear_A",
            "Mahajani", "Manichaean", "Mende_Kikakui", "Modi", "Mro",
            "Old_North_Arabian", "Nabataean", "Palmyrene", "Pau_Cin_Hau",
            "Old_Permic", "Psalter_Pahlavi", "Siddham", "Khudawadi",
            "Tirhuta", "Warang_Citi", "Ahom", "Anatolian_Hieroglyphs",
            "Hatran", "Multani", "Old_Hungarian", "SignWriting", "Adlam",
            "Bhaiksuki", "Marchen", "Newa", "Osage", "Tangut",
            "Masaram_Gondi", "Nushu", "Soyombo", "Zanabazar_Square",
            "Dogra", "Gunjala_Gondi", "Makasar", "Medefaidrin",
            "Hanifi_Rohingya", "Sogdian", "Old_Sogdian", "Elymaic",
            "Nandinagari", "Nyiakeng_Puachue_Hmong", "Wancho", "Chorasmian",
            "Dives_Akuru", "Khitan_Small_Script", "Yezidi", "Cypro_Minoan",
            "Old_Uyghur", "Tangsa", "Toto", "Vithkuqi", "Kawi",
            "Nag_Mundari", "Garay", "Gurung_Khema", "Kirat_Rai", "Ol_Onal",
            "Sunuwar", "Todhri", "Tulu_Tigalari", "Sidetic", "Tai_Yo",
            "Tolong_Siki", "Beria_Erfe", "Katakana_Or_Hiragana"};
        const static std::vector<std::string> aliases = {{
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "Qaai", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "Qaac", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", ""}};
    }

    namespace BC_ns {
        enum value_t {
            L, R, AL, ET, EN, ES, AN, CS, B, S, WS, ON, BN, NSM, LRO, RLO,
            LRE, RLE, PDF, LRI, RLI, FSI, PDI};
        const static std::vector<std::string> enum_names = {
            "L", "R", "AL", "ET", "EN", "ES", "AN", "CS", "B", "S", "WS",
            "ON", "BN", "NSM", "LRO", "RLO", "LRE", "RLE", "PDF", "LRI",
            "RLI", "FSI", "PDI"};
        const static std::vector<std::string> value_names = {
            "Left_To_Right", "Right_To_Left", "Arabic_Letter",
            "European_Terminator", "European_Number", "European_Separator",
            "Arabic_Number", "Common_Separator", "Paragraph_Separator",
            "Segment_Separator", "White_Space", "Other_Neutral",
            "Boundary_Neutral", "Nonspacing_Mark", "Left_To_Right_Override",
            "Right_To_Left_Override", "Left_To_Right_Embedding",
            "Right_To_Left_Embedding", "Pop_Directional_Format",
            "Left_To_Right_Isolate", "Right_To_Left_Isolate",
            "First_Strong_Isolate", "Pop_Directional_Isolate"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace BPT_ns {
        enum value_t {
            n, o, c};
        const static std::vector<std::string> enum_names = {
            "n", "o", "c"};
        const static std::vector<std::string> value_names = {
            "None", "Open", "Close"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace CCC_ns {
        enum value_t {
            NR, OV, HANR, NK, KV, VR, CCC10, CCC11, CCC12, CCC13, CCC14,
            CCC15, CCC16, CCC17, CCC18, CCC19, CCC20, CCC21, CCC22, CCC23,
            CCC24, CCC25, CCC26, CCC27, CCC28, CCC29, CCC30, CCC31, CCC32,
            CCC33, CCC34, CCC35, CCC36, CCC84, CCC91, CCC103, CCC107,
            CCC118, CCC122, CCC129, CCC130, CCC132, CCC133, ATBL, ATB, ATA,
            ATAR, BL, B, BR, L, R, AL, A, AR, DB, DA, IS
        };
        const uint16_t enum_val[] = {
              0, 1, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
            21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
            84, 91, 103, 107, 118, 122, 129, 130, 132, 133, 200, 202, 214,
            216, 218, 220, 222, 224, 226, 228, 230, 232, 233, 234, 240};
        const static std::vector<std::string> enum_names = {
            "NR", "OV", "HANR", "NK", "KV", "VR", "CCC10", "CCC11", "CCC12",
            "CCC13", "CCC14", "CCC15", "CCC16", "CCC17", "CCC18", "CCC19",
            "CCC20", "CCC21", "CCC22", "CCC23", "CCC24", "CCC25", "CCC26",
            "CCC27", "CCC28", "CCC29", "CCC30", "CCC31", "CCC32", "CCC33",
            "CCC34", "CCC35", "CCC36", "CCC84", "CCC91", "CCC103", "CCC107",
            "CCC118", "CCC122", "CCC129", "CCC130", "CCC132", "CCC133",
            "ATBL", "ATB", "ATA", "ATAR", "BL", "B", "BR", "L", "R", "AL",
            "A", "AR", "DB", "DA", "IS"};
        const static std::vector<std::string> value_names = {
            "Not_Reordered", "Overlay", "Han_Reading", "Nukta",
            "Kana_Voicing", "Virama", "CCC10", "CCC11", "CCC12", "CCC13",
            "CCC14", "CCC15", "CCC16", "CCC17", "CCC18", "CCC19", "CCC20",
            "CCC21", "CCC22", "CCC23", "CCC24", "CCC25", "CCC26", "CCC27",
            "CCC28", "CCC29", "CCC30", "CCC31", "CCC32", "CCC33", "CCC34",
            "CCC35", "CCC36", "CCC84", "CCC91", "CCC103", "CCC107",
            "CCC118", "CCC122", "CCC129", "CCC130", "CCC132", "CCC133",
            "Attached_Below_Left", "Attached_Below", "Attached_Above",
            "Attached_Above_Right", "Below_Left", "Below", "Below_Right",
            "Left", "Right", "Above_Left", "Above", "Above_Right",
            "Double_Below", "Double_Above", "Iota_Subscript"};
        const static std::vector<std::string> aliases = {{
            "0", "1", "6", "7", "8", "9", "10", "11", "12", "13", "14",
            "15", "16", "17", "18", "19", "20", "21", "22", "23", "24",
            "25", "26", "27", "28", "29", "30", "31", "32", "33", "34",
            "35", "36", "84", "91", "103", "107", "118", "122", "129",
            "130", "132", "133", "200", "202", "214", "216", "218", "220",
            "222", "224", "226", "228", "230", "232", "233", "234", "240"}};
    }

    namespace DT_ns {
        enum value_t {
            None, Can, Com, Font, Nb, Init, Med, Fin, Iso, Enc, Sup, Sub,
            Vert, Wide, Nar, Sml, Sqr, Fra};
        const static std::vector<std::string> enum_names = {
            "None", "Can", "Com", "Font", "Nb", "Init", "Med", "Fin", "Iso",
            "Enc", "Sup", "Sub", "Vert", "Wide", "Nar", "Sml", "Sqr", "Fra"};
        const static std::vector<std::string> value_names = {
            "None", "Canonical", "Compat", "Font", "Nobreak", "Initial",
            "Medial", "Final", "Isolated", "Circle", "Super", "Sub",
            "Vertical", "Wide", "Narrow", "Small", "Square", "Fraction"};
        const static std::vector<std::string> aliases = {{
            "none", "can", "com", "font", "nb", "init", "med", "fin", "iso",
            "enc", "sup", "sub", "vert", "wide", "nar", "sml", "sqr", "fra"}};
    }

    namespace EA_ns {
        enum value_t {
            N, Na, A, W, H, F};
        const static std::vector<std::string> enum_names = {
            "N", "Na", "A", "W", "H", "F"};
        const static std::vector<std::string> value_names = {
            "Neutral", "Narrow", "Ambiguous", "Wide", "Halfwidth",
            "Fullwidth"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace GC_ns {
        enum value_t {
            Cn, Lu, Ll, Lt, Lm, Lo, Mn, Me, Mc, Nd, Nl, No, Zs, Zl, Zp, Cc,
            Cf, Co, Cs, Pd, Ps, Pe, Pc, Po, Sm, Sc, Sk, So, Pi, Pf, C, L,
            LC, M, N, P, S, Z};
        const static std::vector<std::string> enum_names = {
            "Cn", "Lu", "Ll", "Lt", "Lm", "Lo", "Mn", "Me", "Mc", "Nd",
            "Nl", "No", "Zs", "Zl", "Zp", "Cc", "Cf", "Co", "Cs", "Pd",
            "Ps", "Pe", "Pc", "Po", "Sm", "Sc", "Sk", "So", "Pi", "Pf", "C",
            "L", "LC", "M", "N", "P", "S", "Z"};
        const static std::vector<std::string> value_names = {
            "Unassigned", "Uppercase_Letter", "Lowercase_Letter",
            "Titlecase_Letter", "Modifier_Letter", "Other_Letter",
            "Nonspacing_Mark", "Enclosing_Mark", "Spacing_Mark",
            "Decimal_Number", "Letter_Number", "Other_Number",
            "Space_Separator", "Line_Separator", "Paragraph_Separator",
            "Control", "Format", "Private_Use", "Surrogate",
            "Dash_Punctuation", "Open_Punctuation", "Close_Punctuation",
            "Connector_Punctuation", "Other_Punctuation", "Math_Symbol",
            "Currency_Symbol", "Modifier_Symbol", "Other_Symbol",
            "Initial_Punctuation", "Final_Punctuation", "Other", "Letter",
            "Cased_Letter", "Mark", "Number", "Punctuation", "Symbol",
            "Separator"};
        const static std::vector<std::string> aliases = {{
            "", "", "", "", "", "", "", "", "", "digit", "", "", "", "", "",
            "cntrl", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "Combining_Mark", "", "punct", "", ""}};
    }

    namespace GCB_ns {
        enum value_t {
            XX, PP, CR, LF, CN, EX, RI, SM, L, V, T, LV, LVT, ZWJ, EB, EBG,
            EM, GAZ};
        const static std::vector<std::string> enum_names = {
            "XX", "PP", "CR", "LF", "CN", "EX", "RI", "SM", "L", "V", "T",
            "LV", "LVT", "ZWJ", "EB", "EBG", "EM", "GAZ"};
        const static std::vector<std::string> value_names = {
            "Other", "Prepend", "CR", "LF", "Control", "Extend",
            "Regional_Indicator", "SpacingMark", "L", "V", "T", "LV", "LVT",
            "ZWJ", "E_Base", "E_Base_GAZ", "E_Modifier", "Glue_After_Zwj"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace HST_ns {
        enum value_t {
            NA, L, V, T, LV, LVT};
        const static std::vector<std::string> enum_names = {
            "NA", "L", "V", "T", "LV", "LVT"};
        const static std::vector<std::string> value_names = {
            "Not_Applicable", "Leading_Jamo", "Vowel_Jamo", "Trailing_Jamo",
            "LV_Syllable", "LVT_Syllable"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace INCB_ns {
        enum value_t {
            None, Linker, Consonant, Extend};
        const static std::vector<std::string> enum_names = {
            "None", "Linker", "Consonant", "Extend"};
        const static std::vector<std::string> value_names = {
            "None", "Linker", "Consonant", "Extend"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace INPC_ns {
        enum value_t {
            NA, Right, Left, Visual_Order_Left, Left_And_Right, Top, Bottom,
            Top_And_Bottom, Top_And_Right, Top_And_Left,
            Top_And_Left_And_Right, Bottom_And_Right, Bottom_And_Left,
            Top_And_Bottom_And_Right, Top_And_Bottom_And_Left, Overstruck};
        const static std::vector<std::string> enum_names = {
            "NA", "Right", "Left", "Visual_Order_Left", "Left_And_Right",
            "Top", "Bottom", "Top_And_Bottom", "Top_And_Right",
            "Top_And_Left", "Top_And_Left_And_Right", "Bottom_And_Right",
            "Bottom_And_Left", "Top_And_Bottom_And_Right",
            "Top_And_Bottom_And_Left", "Overstruck"};
        const static std::vector<std::string> value_names = {
            "Not_Applicable", "Right", "Left", "Visual_Order_Left",
            "Left_And_Right", "Top", "Bottom", "Top_And_Bottom",
            "Top_And_Right", "Top_And_Left", "Top_And_Left_And_Right",
            "Bottom_And_Right", "Bottom_And_Left",
            "Top_And_Bottom_And_Right", "Top_And_Bottom_And_Left",
            "Overstruck"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace INSC_ns {
        enum value_t {
            Other, Bindu, Visarga, Avagraha, Nukta, Virama, Pure_Killer,
            Reordering_Killer, Invisible_Stacker, Vowel_Independent,
            Vowel_Dependent, Vowel, Consonant_Placeholder, Consonant,
            Consonant_Dead, Consonant_With_Stacker, Consonant_Prefixed,
            Consonant_Preceding_Repha, Consonant_Initial_Postfixed,
            Consonant_Succeeding_Repha, Consonant_Subjoined,
            Consonant_Medial, Consonant_Final, Consonant_Head_Letter,
            Modifying_Letter, Tone_Letter, Tone_Mark, Gemination_Mark,
            Cantillation_Mark, Register_Shifter, Syllable_Modifier,
            Consonant_Killer, Non_Joiner, Joiner, Number_Joiner, Number,
            Brahmi_Joining_Number};
        const static std::vector<std::string> enum_names = {
            "Other", "Bindu", "Visarga", "Avagraha", "Nukta", "Virama",
            "Pure_Killer", "Reordering_Killer", "Invisible_Stacker",
            "Vowel_Independent", "Vowel_Dependent", "Vowel",
            "Consonant_Placeholder", "Consonant", "Consonant_Dead",
            "Consonant_With_Stacker", "Consonant_Prefixed",
            "Consonant_Preceding_Repha", "Consonant_Initial_Postfixed",
            "Consonant_Succeeding_Repha", "Consonant_Subjoined",
            "Consonant_Medial", "Consonant_Final", "Consonant_Head_Letter",
            "Modifying_Letter", "Tone_Letter", "Tone_Mark",
            "Gemination_Mark", "Cantillation_Mark", "Register_Shifter",
            "Syllable_Modifier", "Consonant_Killer", "Non_Joiner", "Joiner",
            "Number_Joiner", "Number", "Brahmi_Joining_Number"};
        const static std::vector<std::string> value_names = {
            "Other", "Bindu", "Visarga", "Avagraha", "Nukta", "Virama",
            "Pure_Killer", "Reordering_Killer", "Invisible_Stacker",
            "Vowel_Independent", "Vowel_Dependent", "Vowel",
            "Consonant_Placeholder", "Consonant", "Consonant_Dead",
            "Consonant_With_Stacker", "Consonant_Prefixed",
            "Consonant_Preceding_Repha", "Consonant_Initial_Postfixed",
            "Consonant_Succeeding_Repha", "Consonant_Subjoined",
            "Consonant_Medial", "Consonant_Final", "Consonant_Head_Letter",
            "Modifying_Letter", "Tone_Letter", "Tone_Mark",
            "Gemination_Mark", "Cantillation_Mark", "Register_Shifter",
            "Syllable_Modifier", "Consonant_Killer", "Non_Joiner", "Joiner",
            "Number_Joiner", "Number", "Brahmi_Joining_Number"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace JG_ns {
        enum value_t {
            No_Joining_Group, Ain, Alaph, Alef, Beh, Beth, Dal, Dalath_Rish,
            E, Feh, Final_Semkath, Gaf, Gamal, Hah, Teh_Marbuta_Goal, He,
            Heh, Heh_Goal, Heth, Kaf, Kaph, Knotted_Heh, Lam, Lamadh, Meem,
            Mim, Noon, Nun, Pe, Qaf, Qaph, Reh, Reversed_Pe, Sad, Sadhe,
            Seen, Semkath, Shin, Swash_Kaf, Tah, Taw, Teh_Marbuta, Teth,
            Waw, Syriac_Waw, Yeh, Yeh_Barree, Yeh_With_Tail, Yudh, Yudh_He,
            Zain, Zhain, Khaph, Fe, Burushaski_Yeh_Barree, Farsi_Yeh, Nya,
            Rohingya_Yeh, Straight_Waw, Manichaean_Aleph, Manichaean_Ayin,
            Manichaean_Beth, Manichaean_Daleth, Manichaean_Dhamedh,
            Manichaean_Five, Manichaean_Gimel, Manichaean_Heth,
            Manichaean_Hundred, Manichaean_Kaph, Manichaean_Lamedh,
            Manichaean_Mem, Manichaean_Nun, Manichaean_One, Manichaean_Pe,
            Manichaean_Qoph, Manichaean_Resh, Manichaean_Sadhe,
            Manichaean_Samekh, Manichaean_Taw, Manichaean_Ten,
            Manichaean_Teth, Manichaean_Thamedh, Manichaean_Twenty,
            Manichaean_Waw, Manichaean_Yodh, Manichaean_Zayin, African_Feh,
            African_Qaf, African_Noon, Malayalam_Nga, Malayalam_Ja,
            Malayalam_Nya, Malayalam_Tta, Malayalam_Nna, Malayalam_Nnna,
            Malayalam_Bha, Malayalam_Ra, Malayalam_Lla, Malayalam_Llla,
            Malayalam_Ssa, Hanifi_Rohingya_Pa, Hanifi_Rohingya_Kinna_Ya,
            Thin_Yeh, Vertical_Tail, Kashmiri_Yeh, Thin_Noon};
        const static std::vector<std::string> enum_names = {
            "No_Joining_Group", "Ain", "Alaph", "Alef", "Beh", "Beth",
            "Dal", "Dalath_Rish", "E", "Feh", "Final_Semkath", "Gaf",
            "Gamal", "Hah", "Teh_Marbuta_Goal", "He", "Heh", "Heh_Goal",
            "Heth", "Kaf", "Kaph", "Knotted_Heh", "Lam", "Lamadh", "Meem",
            "Mim", "Noon", "Nun", "Pe", "Qaf", "Qaph", "Reh", "Reversed_Pe",
            "Sad", "Sadhe", "Seen", "Semkath", "Shin", "Swash_Kaf", "Tah",
            "Taw", "Teh_Marbuta", "Teth", "Waw", "Syriac_Waw", "Yeh",
            "Yeh_Barree", "Yeh_With_Tail", "Yudh", "Yudh_He", "Zain",
            "Zhain", "Khaph", "Fe", "Burushaski_Yeh_Barree", "Farsi_Yeh",
            "Nya", "Rohingya_Yeh", "Straight_Waw", "Manichaean_Aleph",
            "Manichaean_Ayin", "Manichaean_Beth", "Manichaean_Daleth",
            "Manichaean_Dhamedh", "Manichaean_Five", "Manichaean_Gimel",
            "Manichaean_Heth", "Manichaean_Hundred", "Manichaean_Kaph",
            "Manichaean_Lamedh", "Manichaean_Mem", "Manichaean_Nun",
            "Manichaean_One", "Manichaean_Pe", "Manichaean_Qoph",
            "Manichaean_Resh", "Manichaean_Sadhe", "Manichaean_Samekh",
            "Manichaean_Taw", "Manichaean_Ten", "Manichaean_Teth",
            "Manichaean_Thamedh", "Manichaean_Twenty", "Manichaean_Waw",
            "Manichaean_Yodh", "Manichaean_Zayin", "African_Feh",
            "African_Qaf", "African_Noon", "Malayalam_Nga", "Malayalam_Ja",
            "Malayalam_Nya", "Malayalam_Tta", "Malayalam_Nna",
            "Malayalam_Nnna", "Malayalam_Bha", "Malayalam_Ra",
            "Malayalam_Lla", "Malayalam_Llla", "Malayalam_Ssa",
            "Hanifi_Rohingya_Pa", "Hanifi_Rohingya_Kinna_Ya", "Thin_Yeh",
            "Vertical_Tail", "Kashmiri_Yeh", "Thin_Noon"};
        const static std::vector<std::string> value_names = {
            "No_Joining_Group", "Ain", "Alaph", "Alef", "Beh", "Beth",
            "Dal", "Dalath_Rish", "E", "Feh", "Final_Semkath", "Gaf",
            "Gamal", "Hah", "Teh_Marbuta_Goal", "He", "Heh", "Heh_Goal",
            "Heth", "Kaf", "Kaph", "Knotted_Heh", "Lam", "Lamadh", "Meem",
            "Mim", "Noon", "Nun", "Pe", "Qaf", "Qaph", "Reh", "Reversed_Pe",
            "Sad", "Sadhe", "Seen", "Semkath", "Shin", "Swash_Kaf", "Tah",
            "Taw", "Teh_Marbuta", "Teth", "Waw", "Syriac_Waw", "Yeh",
            "Yeh_Barree", "Yeh_With_Tail", "Yudh", "Yudh_He", "Zain",
            "Zhain", "Khaph", "Fe", "Burushaski_Yeh_Barree", "Farsi_Yeh",
            "Nya", "Rohingya_Yeh", "Straight_Waw", "Manichaean_Aleph",
            "Manichaean_Ayin", "Manichaean_Beth", "Manichaean_Daleth",
            "Manichaean_Dhamedh", "Manichaean_Five", "Manichaean_Gimel",
            "Manichaean_Heth", "Manichaean_Hundred", "Manichaean_Kaph",
            "Manichaean_Lamedh", "Manichaean_Mem", "Manichaean_Nun",
            "Manichaean_One", "Manichaean_Pe", "Manichaean_Qoph",
            "Manichaean_Resh", "Manichaean_Sadhe", "Manichaean_Samekh",
            "Manichaean_Taw", "Manichaean_Ten", "Manichaean_Teth",
            "Manichaean_Thamedh", "Manichaean_Twenty", "Manichaean_Waw",
            "Manichaean_Yodh", "Manichaean_Zayin", "African_Feh",
            "African_Qaf", "African_Noon", "Malayalam_Nga", "Malayalam_Ja",
            "Malayalam_Nya", "Malayalam_Tta", "Malayalam_Nna",
            "Malayalam_Nnna", "Malayalam_Bha", "Malayalam_Ra",
            "Malayalam_Lla", "Malayalam_Llla", "Malayalam_Ssa",
            "Hanifi_Rohingya_Pa", "Hanifi_Rohingya_Kinna_Ya", "Thin_Yeh",
            "Vertical_Tail", "Kashmiri_Yeh", "Thin_Noon"};
        const static std::vector<std::string> aliases = {{
            "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "Hamza_On_Heh_Goal", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}};
    }

    namespace JT_ns {
        enum value_t {
            U, C, D, R, L, T};
        const static std::vector<std::string> enum_names = {
            "U", "C", "D", "R", "L", "T"};
        const static std::vector<std::string> value_names = {
            "Non_Joining", "Join_Causing", "Dual_Joining", "Right_Joining",
            "Left_Joining", "Transparent"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace LB_ns {
        enum value_t {
            XX, CM, BA, LF, BK, CR, SP, EX, QU, AL, PR, PO, OP, CP, IS, HY,
            SY, NU, CL, NL, GL, AI, BB, HH, HL, SA, JL, JV, JT, NS, AK, VI,
            AS, ID, VF, ZW, ZWJ, B2, IN, WJ, EB, CJ, H2, H3, SG, CB, AP, RI,
            EM};
        const static std::vector<std::string> enum_names = {
            "XX", "CM", "BA", "LF", "BK", "CR", "SP", "EX", "QU", "AL",
            "PR", "PO", "OP", "CP", "IS", "HY", "SY", "NU", "CL", "NL",
            "GL", "AI", "BB", "HH", "HL", "SA", "JL", "JV", "JT", "NS",
            "AK", "VI", "AS", "ID", "VF", "ZW", "ZWJ", "B2", "IN", "WJ",
            "EB", "CJ", "H2", "H3", "SG", "CB", "AP", "RI", "EM"};
        const static std::vector<std::string> value_names = {
            "Unknown", "Combining_Mark", "Break_After", "Line_Feed",
            "Mandatory_Break", "Carriage_Return", "Space", "Exclamation",
            "Quotation", "Alphabetic", "Prefix_Numeric", "Postfix_Numeric",
            "Open_Punctuation", "Close_Parenthesis", "Infix_Numeric",
            "Hyphen", "Break_Symbols", "Numeric", "Close_Punctuation",
            "Next_Line", "Glue", "Ambiguous", "Break_Before",
            "Unambiguous_Hyphen", "Hebrew_Letter", "Complex_Context", "JL",
            "JV", "JT", "Nonstarter", "Aksara", "Virama", "Aksara_Start",
            "Ideographic", "Virama_Final", "ZWSpace", "ZWJ", "Break_Both",
            "Inseparable", "Word_Joiner", "E_Base",
            "Conditional_Japanese_Starter", "H2", "H3", "Surrogate",
            "Contingent_Break", "Aksara_Prebase", "Regional_Indicator",
            "E_Modifier"};
        const static std::vector<std::string> aliases = {{
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "Inseperable", "", "", "", "", "", "",
            "", "", "", ""}};
    }

    namespace NFC_QC_ns {
        enum value_t {
            Y, N, M};
        const static std::vector<std::string> enum_names = {
            "Y", "N", "M"};
        const static std::vector<std::string> value_names = {
            "Yes", "No", "Maybe"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace NFD_QC_ns {
        enum value_t {
            Y, N};
        const static std::vector<std::string> enum_names = {
            "Y", "N"};
        const static std::vector<std::string> value_names = {
            "Yes", "No"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace NFKC_QC_ns {
        enum value_t {
            Y, N, M};
        const static std::vector<std::string> enum_names = {
            "Y", "N", "M"};
        const static std::vector<std::string> value_names = {
            "Yes", "No", "Maybe"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace NFKD_QC_ns {
        enum value_t {
            Y, N};
        const static std::vector<std::string> enum_names = {
            "Y", "N"};
        const static std::vector<std::string> value_names = {
            "Yes", "No"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace NT_ns {
        enum value_t {
            None, Nu, Di, De};
        const static std::vector<std::string> enum_names = {
            "None", "Nu", "Di", "De"};
        const static std::vector<std::string> value_names = {
            "None", "Numeric", "Digit", "Decimal"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace SB_ns {
        enum value_t {
            XX, CR, LF, EX, SE, FO, SP, LO, UP, LE, NU, AT, ST, CL, SC};
        const static std::vector<std::string> enum_names = {
            "XX", "CR", "LF", "EX", "SE", "FO", "SP", "LO", "UP", "LE",
            "NU", "AT", "ST", "CL", "SC"};
        const static std::vector<std::string> value_names = {
            "Other", "CR", "LF", "Extend", "Sep", "Format", "Sp", "Lower",
            "Upper", "OLetter", "Numeric", "ATerm", "STerm", "Close",
            "SContinue"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace VO_ns {
        enum value_t {
            R, U, Tr, Tu};
        const static std::vector<std::string> enum_names = {
            "R", "U", "Tr", "Tu"};
        const static std::vector<std::string> value_names = {
            "Rotated", "Upright", "Transformed_Rotated",
            "Transformed_Upright"};
        const static std::vector<std::string> aliases = {{
            }};
    }

    namespace WB_ns {
        enum value_t {
            XX, DQ, SQ, HL, CR, LF, NL, Extend, RI, FO, KA, LE, ML, MN, MB,
            NU, EX, ZWJ, WSegSpace, EB, EBG, EM, GAZ};
        const static std::vector<std::string> enum_names = {
            "XX", "DQ", "SQ", "HL", "CR", "LF", "NL", "Extend", "RI", "FO",
            "KA", "LE", "ML", "MN", "MB", "NU", "EX", "ZWJ", "WSegSpace",
            "EB", "EBG", "EM", "GAZ"};
        const static std::vector<std::string> value_names = {
            "Other", "Double_Quote", "Single_Quote", "Hebrew_Letter", "CR",
            "LF", "Newline", "Extend", "Regional_Indicator", "Format",
            "Katakana", "ALetter", "MidLetter", "MidNum", "MidNumLet",
            "Numeric", "ExtendNumLet", "ZWJ", "WSegSpace", "E_Base",
            "E_Base_GAZ", "E_Modifier", "Glue_After_Zwj"};
        const static std::vector<std::string> aliases = {{
            }};
    }
}

#endif
