/*
 *  Part of the Parabix Project, under the Open Software License 3.0.
 *  SPDX-License-Identifier: OSL-3.0
 */

#include <pablo/passes/passes.h>

#include <pablo/compiler/pablo_kernel.h>
#include <pablo/passes/pablo_simplifier.hpp>
#include <pablo/passes/codemotionpass.h>
#include <pablo/passes/distributivepass.h>
#include <pablo/passes/schedulingprepass.h>
#include <pablo/passes/flattenif.hpp>
#include <pablo/compiler/pabloverifier.hpp>
#include <pablo/compiler/printer_pablos.h>
#include <llvm/Support/raw_ostream.h>
#include <toolchain/toolchain.h>
#include <pablo/toolchain/pablo_toolchain.h>
#include <pablo/compiler/pablo_illustratorpass.h>
#include <boost/regex.hpp>
#include <mutex>

using namespace llvm;

namespace pablo {

namespace {

// pablo_function_passes() runs per-kernel on whichever compile thread happens
// to process that kernel, so under multi-threaded compilation, multiple
// kernels' -ShowPablo/-ShowOptimizedPablo dumps can be in flight at once.
// PabloPrinter::print() makes an unbounded number of separate writes to its
// raw_ostream, none of which are atomic with respect to each other, so
// writing straight to errs() (or to the same output file, in the file-output
// case) interleaves those writes into corrupted, unreadable output. Format
// each kernel's dump into an in-memory buffer first -- no locking needed for
// that, since it doesn't touch shared state -- then take this lock only to
// perform the actual write (and, for the file-output case, the
// create-vs-append flag toggle, which was also an unguarded data race) as a
// single atomic step.
std::mutex PabloPrintMutex;

void printPabloKernelAtomically(PabloKernel * const kernel, const StringRef banner,
                                 const std::string & outputPath, sys::fs::OpenFlags & appendFlag) {
    std::string buffer;
    raw_string_ostream buf(buffer);
    if (outputPath.empty()) {
        buf << banner;
    }
    PabloPrinter::print(kernel, buf);
    buf.flush();

    std::lock_guard<std::mutex> lock(PabloPrintMutex);
    if (outputPath.empty()) {
        errs() << buffer;
    } else {
        std::error_code error;
        llvm::raw_fd_ostream out(outputPath, error, appendFlag);
        out << buffer;
        appendFlag = sys::fs::OpenFlags::OF_Append;   // append subsequent Pablo kernels
    }
}

} // anonymous namespace

void pablo_function_passes(PabloKernel * kernel) {

    if (ShowPabloOption != codegen::OmittedOption) {
        //Print to the terminal the AST that was generated by the pararallel bit-stream compiler.
        bool print_kernel = true;
        if (!codegen::ShowIRFilter.empty()) {
            std::string kernelName = kernel->getName();
            const boost::regex RegexFilter(codegen::ShowIRFilter);
            print_kernel = boost::regex_search(kernelName, RegexFilter);
        }
        if (print_kernel) {
            printPabloKernelAtomically(kernel, "### Initial Pablo AST ###\n", ShowPabloOption, PabloOutputFileFlag);
        }
    }

#ifdef NDEBUG
    const auto verify = pablo::CompileOptionIsSet(VerifyPablo);
#else
    const auto verify = true;
#endif

    if (LLVM_UNLIKELY(verify)) {
        PabloVerifier::verify(kernel, "creation");
    }

    if (LLVM_UNLIKELY(!pablo::PabloIllustrateBitstreamRegEx.empty() || !pablo::PabloIllustrateKernelRegEx.empty())) {
        runIllustratorPass(kernel);
        if (LLVM_UNLIKELY(verify)) {
            PabloVerifier::verify(kernel, "post-illustrator-pass");
        }
    }
    // Scan through the pablo code and perform DCE and CSE
    if (Flatten){
        FlattenIf::transform(kernel);
        if (LLVM_UNLIKELY(verify)) {
            PabloVerifier::verify(kernel, "post-distributive-pass");
        }
    }
    if (LLVM_LIKELY(!CompileOptionIsSet(DisableSimplification))) {
        Simplifier::optimize(kernel);
        if (LLVM_UNLIKELY(verify)) {
            PabloVerifier::verify(kernel, "post-simplification");
        }
    }
    if (CompileOptionIsSet(EnableDistribution)) {
        DistributivePass::optimize(kernel);
        if (LLVM_UNLIKELY(verify)) {
            PabloVerifier::verify(kernel, "post-distributive-pass");
        }
    }
    if (LLVM_LIKELY(!CompileOptionIsSet(DisableCodeMotion))) {
        CodeMotionPass::optimize(kernel);
        if (LLVM_UNLIKELY(verify)) {
            PabloVerifier::verify(kernel, "post-code-motion");
        }
    }
    if (CompileOptionIsSet(EnableSchedulingPrePass)) {
        SchedulingPrePass::optimize(kernel);
        if (LLVM_UNLIKELY(verify)) {
            PabloVerifier::verify(kernel, "post-scheduling-prepass");
        }
    }
    if (ShowOptimizedPabloOption != codegen::OmittedOption) {
        printPabloKernelAtomically(kernel, "### Final Pablo AST ###\n", ShowOptimizedPabloOption, PabloOptimizedOutputFileFlag);
    }
}

}
