#pragma once
/*
 *  Part of the Parabix Project, under the Open Software License 3.0.
 *  SPDX-License-Identifier: OSL-3.0
 *
 *  This file is generated by generate_GB_18030_data.py - manual edits may be lost.
 */

#include <vector>
#include <ucd/core/unicode_set.h>

std::vector<UCD::codepoint_t> & get_GB_DoubleByteTable();

std::vector<std::pair<unsigned, unsigned>> & get_GB_RangeTable();

