/*
 *  Part of the Parabix Project, under the Open Software License 3.0.
 *  SPDX-License-Identifier: OSL-3.0
 */

#include <pablo/passes.h>

#include <pablo/pablo_kernel.h>
#include <pablo/pablo_simplifier.hpp>
#include <pablo/codemotionpass.h>
#include <pablo/distributivepass.h>
#include <pablo/schedulingprepass.h>
#include <pablo/flattenif.hpp>
#include <pablo/pabloverifier.hpp>
#include <pablo/printer_pablos.h>
#include <llvm/Support/raw_ostream.h>
#include <toolchain/toolchain.h>
#include <pablo/pablo_toolchain.h>
#include <pablo/pablo_illustratorpass.h>
#include <boost/regex.hpp>

#if LLVM_VERSION_INTEGER < LLVM_VERSION_CODE(7, 0, 0)
#define OF_Append F_Append
#endif


using namespace llvm;

namespace pablo {

void pablo_function_passes(PabloKernel * kernel) {

    if (ShowPabloOption != codegen::OmittedOption) {
        //Print to the terminal the AST that was generated by the pararallel bit-stream compiler.
        bool print_kernel = true;
        if (!codegen::ShowIRFilter.empty()) {
            std::string kernelName = kernel->getName();
            const boost::regex RegexFilter(codegen::ShowIRFilter);
            print_kernel = boost::regex_search(kernelName, RegexFilter);
        }
        if (print_kernel) {
            if (ShowPabloOption.empty()) {
                errs() << "### Initial Pablo AST ###\n";
                PabloPrinter::print(kernel, errs());
            } else {
                std::error_code error;
                llvm::raw_fd_ostream out(ShowPabloOption, error, PabloOutputFileFlag);
                PabloPrinter::print(kernel, out);
                PabloOutputFileFlag = sys::fs::OpenFlags::OF_Append;   // append subsequent Pablo kernels
            }
        }
    }

#ifdef NDEBUG
    const auto verify = pablo::DebugOptionIsSet(VerifyPablo);
#else
    const auto verify = true;
#endif

    if (LLVM_UNLIKELY(verify)) {
        PabloVerifier::verify(kernel, "creation");
    }

    if (LLVM_UNLIKELY(!pablo::PabloIllustrateBitstreamRegEx.empty() || !pablo::PabloIllustrateKernelRegEx.empty())) {
        runIllustratorPass(kernel);
        if (LLVM_UNLIKELY(verify)) {
            PabloVerifier::verify(kernel, "post-illustrator-pass");
        }
    }
    // Scan through the pablo code and perform DCE and CSE
    if (Flatten){
        FlattenIf::transform(kernel);
        if (LLVM_UNLIKELY(verify)) {
            PabloVerifier::verify(kernel, "post-distributive-pass");
        }
    }
    if (LLVM_LIKELY(!CompileOptionIsSet(DisableSimplification))) {
        Simplifier::optimize(kernel);
        if (LLVM_UNLIKELY(verify)) {
            PabloVerifier::verify(kernel, "post-simplification");
        }
    }
    if (CompileOptionIsSet(EnableDistribution)) {
        DistributivePass::optimize(kernel);
        if (LLVM_UNLIKELY(verify)) {
            PabloVerifier::verify(kernel, "post-distributive-pass");
        }
    }
    if (LLVM_LIKELY(!CompileOptionIsSet(DisableCodeMotion))) {
        CodeMotionPass::optimize(kernel);
        if (LLVM_UNLIKELY(verify)) {
            PabloVerifier::verify(kernel, "post-code-motion");
        }
    }
    if (CompileOptionIsSet(EnableSchedulingPrePass)) {
        SchedulingPrePass::optimize(kernel);
        if (LLVM_UNLIKELY(verify)) {
            PabloVerifier::verify(kernel, "post-scheduling-prepass");
        }
    }
    if (ShowOptimizedPabloOption != codegen::OmittedOption) {
        if (ShowOptimizedPabloOption.empty()) {
            //Print to the terminal the final Pablo AST after optimization.
            errs() << "### Final Pablo AST ###\n";
            PabloPrinter::print(kernel, errs());
        } else {
            std::error_code error;
            llvm::raw_fd_ostream out(ShowOptimizedPabloOption, error, PabloOptimizedOutputFileFlag);
            PabloPrinter::print(kernel, out);
            PabloOptimizedOutputFileFlag = sys::fs::OpenFlags::OF_Append;  // append subsequent Pablo kernels
        }
    }
}

}
